### ISSUE TITLE
T000007: NSEFO Order error code handle

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#10]

**Comment by Kartik-RestAlgo** [comment]
As discussed with Virag sir And Vaibhav sir Possible validation for NSEFO done
Logic and Structure created

**Comment by Kartik-RestAlgo** [comment]
[NSEFO Order error code handle.pdf](https://github.com/RestAlgo/TradingApplication/files/15385347/NSEFO.Order.error.code.handle.pdf)

**Comment by VIRAG-RestAlgo** [comment]
merged in live branch.
