### ISSUE TITLE
Master File already exist then first delete old file and then write new file.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#100]
In Trading App, and all exe, Master File already exist then first delete old file and then write new file.

**Comment by VIRAG-RestAlgo** [comment]
please ask to @Anil-Restalgo if any query

**Comment by VIRAG-RestAlgo** [comment]
Please update your status for this task.

**Comment by Soubhagya-Restalgo** [comment]
this task done 20-05-2024 but i was on leave yesterday(22-05-2024)

**Comment by VIRAG-RestAlgo** [comment]
old backlog task.
This is done and working in live.
