### ISSUE TITLE
Dockabal  form should not be close on escap.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#101]
Dockabal  form should not be close on escap.

if form is in float mode then it can be close by escap.

**Comment by VIRAG-RestAlgo** [comment]
@Anil-Restalgo please add description and discuss with @Soubhagya-Restalgo

**Comment by VIRAG-RestAlgo** [comment]
Due to @Soubhagya-Restalgo  on leave this task allot to @Sakshi-Restalgo

**Comment by Sakshi-Restalgo** [comment]
Development and testing done .
Applying logic for all forms.

**Comment by Sakshi-Restalgo** [comment]
Devlopment done in all forms.

**Comment by VIRAG-RestAlgo** [comment]
Code merge by @Anil-Restalgo and working Ok.

**Comment by VIRAG-RestAlgo** [comment]
@Sakshi-Restalgo   send me Check point.****

**Comment by Sakshi-Restalgo** [comment]
below is my  T101 checkpoint please check and review that

[CheckPoint--EscapInClose.pdf](https://github.com/user-attachments/files/15603302/CheckPoint--EscapInClose.pdf)
