### ISSUE TITLE
Total Net,Buy,Sell Qty in Net Position should be integer value.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#102]
Total Net, Buy, Sell Qty in Net Position should be integer value.

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo

**Comment by Kartik-RestAlgo** [comment]
While New row added in Net Position if column is Of any Quantity than it will be Integer and rest is same as before

**Comment by Kartik-RestAlgo** [comment]
this Task is Merge with Branch Task-95

**Comment by Kartik-RestAlgo** [comment]
[Total Net,Buy,Sell Qty in Net Position should be integer value.pdf](https://github.com/RestAlgo/TradingApplication/files/15385337/Total.Net.Buy.Sell.Qty.in.Net.Position.should.be.integer.value.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done in live version. and testing Ok by me.
