### ISSUE TITLE
In Market Depth Expiry should work as Symbol

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#104]
If user write 22 and get two value 22May2024 and 22June2024 in strike price comobo , and user press tab key then select 1st value 22May2024

**Comment by Usha-Restalgo** [comment]
Task done just have to  use setautocomplete method so moving this task to Devlopment Done

**Comment by VIRAG-RestAlgo** [comment]
Done

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo   send me Check point.

**Comment by Usha-Restalgo** [comment]
below is my chckpoint pdf for task no 104
please check and review it


[104-In Market Depth Expiry should work as Symbol.pdf](https://github.com/user-attachments/files/15604368/104-In.Market.Depth.Expiry.should.work.as.Symbol.pdf)
