### ISSUE TITLE
Change in limit tool bar

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#107]
Rename M2M Limit Utilized to M2M
Rename Margin Utilized to Margin
Add option to show/hide tool bar.
Add Refresh button to refresh utilized limit in tool bar.

**Comment by Kartik-RestAlgo** [comment]
Rename M2M Limit Utilized to M2M
Rename Margin Utilized to Margin
Add option to show/hide tool bar.
completed.

Add Refresh button to refresh utilized limit in tool bar. - Pending
Need to Understand from Pratik Sir

**Comment by Kartik-RestAlgo** [comment]
New menu added in limit bar tool and added a button refresh

**Comment by VIRAG-RestAlgo** [comment]
@Kartik-RestAlgo send checkpoint

**Comment by Kartik-RestAlgo** [comment]
[Change in limit tool bar_t107.pdf](https://github.com/user-attachments/files/15603275/Change.in.limit.tool.bar_t107.pdf)
