### ISSUE TITLE
T000008: Make a new model for normal buy-sell form.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#11]
1 Create new models for Normal Buy and Normal Sell forms.
2 Get data from form and pass it to data provider via new models.

**Comment by Sakshi-Restalgo** [comment]
1-I have created a new model called NormalOrderView for Normal Buy and Normal Sell.
2-The NormalOrderView model is also used by the Normal Buy and Normal Sell controllers in frmcreatewatch to provide data.
3-The NormalOrderView model is used in  Normal Buy and Normal Sell to model to control data provide.

**Comment by VIRAG-RestAlgo** [comment]
code merging is in process by Amanbhai @Aman-Restalgo & @Sakshi-Restalgo

**Comment by Sakshi-Restalgo** [comment]
Merging Done with Aman Bhai

**Comment by VIRAG-RestAlgo** [comment]
Version : VMD_V24_NormalBuySell

**Comment by VIRAG-RestAlgo** [comment]
@Sakshi-Restalgo    send me Check point.

**Comment by Sakshi-Restalgo** [comment]
below is my  T11 checkpoint please check and review that


[CheckPoint_NewBuyNewSell.pdf](https://github.com/user-attachments/files/15604210/CheckPoint_NewBuyNewSell.pdf)
