### ISSUE TITLE
Trading System code merge with Admin module.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#110]
not required create branch for this task.

**Comment by VIRAG-RestAlgo** [comment]
@Aman-Restalgo you have to work in admin module in live version branch.

Please discuss first before you start work.

**Comment by Aman-Restalgo** [comment]
this task already done bye PPB

**Comment by Kartik-RestAlgo** [comment]
As discussed with Virag Sir code merge and 3 to 4 Methods pending to merge,
for that 4 methods need to discuses with Pratik Sir

**Comment by Aman-Restalgo** [comment]
Task done

**Comment by VIRAG-RestAlgo** [comment]
Done.

**Comment by VIRAG-RestAlgo** [comment]
@Aman-Restalgo   send me Check point.

**Comment by Aman-Restalgo** [comment]
I am attached Checkpoint

[T_110_CheckPoint_AdminModule_08-06-2024.pdf](https://github.com/user-attachments/files/15747678/T_110_CheckPoint_AdminModule_08-06-2024.pdf)
