### ISSUE TITLE
Error in log resolved

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#111]
In our log file errors need to resolved.

**Comment by Kartik-RestAlgo** [comment]
1. Set Color formatting in frmOrderBook
2. Set Color formatting in frmTradeBook 
3. if token not found than market depth will not open condition add
4. if(r.mt.best5Buy != null) condition add in onMarketPicture in frmMarketDepth
5. to prevent when list is null in frmAlgoMarketWatch 
6. prevent go on next line when enter pressed in TradeBook
7. prevent go on next line when enter pressed in orderBook
8. order history open if only row contains data in tradebook
9. order history open if only row contains data in Orderbook

**Comment by Kartik-RestAlgo** [comment]
this task is Merge in VMD_T111_22052024

**Comment by VIRAG-RestAlgo** [comment]
Done
