### ISSUE TITLE
In Indices, nearest expiry date

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#114]
As per our requirement we have to find every hr. nearest strike price of current expiry date.

You can get current expiry date by assettoken of scriptmaster memory.

**Comment by Kartik-RestAlgo** [comment]
Updated and merge in Trading system Branch - KAR_T114

**Comment by Kartik-RestAlgo** [comment]
Testing Pending in Live Exe.

**Comment by Kartik-RestAlgo** [comment]
Development done and Testing Pending from Virag Sir.

**Comment by VIRAG-RestAlgo** [comment]
@Kartik-RestAlgo   send me Check point.

**Comment by Kartik-RestAlgo** [comment]
[Nearest expiry date_T114.pdf](https://github.com/user-attachments/files/15603273/Nearest.expiry.date_T114.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done.
checked  in Trading application.
@Kartik-RestAlgo  please add yesterday log file in this task.
