### ISSUE TITLE
Normal Buy and Normal Sell Code merge

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#116]
Normal Buy and Normal Sell Code merge , from any form normal buy and normal sell form should be open new form.

Order modification from order book by new form (new logic).

new logic with SKP.

**Comment by Usha-Restalgo** [comment]
Normal Buy and Normal Sell Code merge , from any form normal buy and normal sell form should be open new form.-merge done

Order modification from order book by new form (new logic).-merge done

**Comment by Usha-Restalgo** [comment]
So moving this task to devlopment done

**Comment by VIRAG-RestAlgo** [comment]
Done

**Comment by VIRAG-RestAlgo** [comment]
Version : VMD_V24_NormalBuySell

**Comment by VIRAG-RestAlgo** [comment]
@Sakshi-Restalgo @Aman-Restalgo send checkpoint

**Comment by Sakshi-Restalgo** [comment]
below is my  T116 checkpoint please check and review that

[CheckPoint_BuySellMerge.pdf](https://github.com/user-attachments/files/15603470/CheckPoint_BuySellMerge.pdf)
