### ISSUE TITLE
Client Fund Form

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#118]
Logic merge from UPM to live exe and remaining logic for real data is required to develop.

**Comment by VIRAG-RestAlgo** [comment]
This task is now running.

**Comment by VIRAG-RestAlgo** [comment]
From my side, Balance and MTM Ok, 
Fresh login or after login above data will refresh.

Margin data will given by PPB,. @pratik-restalgo  from engine.

**Comment by VIRAG-RestAlgo** [comment]
@pratik-restalgo , my ops engine changes also merge with PPB live branch.

**Comment by VIRAG-RestAlgo** [comment]
Done

**Comment by VIRAG-RestAlgo** [comment]
Issue come in live testing

1) Not responding
2) Margin data replace with zero while limit update.

**Comment by VIRAG-RestAlgo** [comment]
3. show in top window.

**Comment by VIRAG-RestAlgo** [comment]
Issue Sr. No 1 & 3 - Resolved. 
Issue Sr. No 2 need to update in engine @pratik-restalgo

**Comment by pratik-restalgo** [comment]
Issue no 2 is resolved in Engine on 30-05-2024.
