### ISSUE TITLE
Multiple Open Forms Show On TaskBar

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#119]
Whenever Form Open Then Form Not Show of multiple in Taskbar For Example Normal Buy And Normal Sell. And Check All Form Like This

if required any help please ask to @Anil-Restalgo

**Comment by Sakshi-Restalgo** [comment]
It's not happening, but I'm trying.

**Comment by Sakshi-Restalgo** [comment]
Development and testing done .
Applying logic for all forms.

**Comment by Sakshi-Restalgo** [comment]
Done logic all forms.

**Comment by VIRAG-RestAlgo** [comment]
Done

**Comment by Sakshi-Restalgo** [comment]
below is my  T119 checkpoint please check and review that

[CheckPoint-ShowInTaskbar.pdf](https://github.com/user-attachments/files/15603590/CheckPoint-ShowInTaskbar.pdf)
