### ISSUE TITLE
Cut Copy  past in normal market watch

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#124]
Requirement : Cut Copy  past in normal market watch

**Comment by Usha-Restalgo** [comment]
Requirement : Cut Copy past in normal market watch-Development Done
So moving this task to Development Done

**Comment by VIRAG-RestAlgo** [comment]
@Kartik-RestAlgo  please update.

**Comment by Kartik-RestAlgo** [comment]
Old Logic Updated and Tested by Virag Sir

**Comment by VIRAG-RestAlgo** [comment]
@Kartik-RestAlgo  Please test in live market tomorrow.

**Comment by Kartik-RestAlgo** [comment]
[Cut, Copy, & Paste in frmCreateWatch.pdf](https://github.com/RestAlgo/TradingApplication/files/15469353/Cut.Copy.Paste.in.frmCreateWatch.pdf)

**Comment by Jill-Restalgo** [comment]
This is not working in Market watch

**Comment by VIRAG-RestAlgo** [comment]
@Sakshi-Restalgo if required any help then ask to @Usha-Restalgo

**Comment by Sakshi-Restalgo** [comment]
Solve the issue in create watch for cut , copy and paste.
devolvement done and testing done for my side.

**Comment by Sakshi-Restalgo** [comment]
Below is my T124 checkpoint please check and review that
[CheckPoint_T124_CutCopyPaste.pdf](https://github.com/user-attachments/files/16736336/CheckPoint_T124_CutCopyPaste.pdf)

**Comment by VIRAG-RestAlgo** [comment]
This task updated in past and working Ok in live.
