### ISSUE TITLE
Copy Exposure % Master form from Trading System

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#125]
Copy Exposure % master form from Trading System developed by Ushaben.

**Comment by Aman-Restalgo** [comment]
I am merging on trading system to admin that's why I am holding this task.

**Comment by Aman-Restalgo** [comment]
Done Logic  pending Model chenges pending discuss with PPB

**Comment by Aman-Restalgo** [comment]
Done this task 

[T_125_CheckPoint_AdminModule_31-05-2024.pdf](https://github.com/user-attachments/files/15509577/T_125_CheckPoint_AdminModule_31-05-2024.pdf)
