### ISSUE TITLE
Cancel order option in right click from order book.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#127]
Cancel order option in right click from order book. (option as per order modification)

**Comment by Sakshi-Restalgo** [comment]
development done for Cancel order option in right click from order book. 

[CheckPoint-CancelOrder.pdf](https://github.com/RestAlgo/TradingApplication/files/15469303/CheckPoint-CancelOrder.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done
