### ISSUE TITLE
Clt + R ma order book entry preference from should be open on normal buy and normal sell

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#128]
Clt + R ma order book entry preference from should be open on normal buy and normal sell

**Comment by VIRAG-RestAlgo** [comment]
@Anil-Restalgo  please check and update.

**Comment by Sakshi-Restalgo** [comment]
Development done for Ctrl+R key press on the normal buy and sell, the order book preference form will open.

[CheckPoint-OrderEnteryPreferenc.pdf](https://github.com/RestAlgo/TradingApplication/files/15469478/CheckPoint-OrderEnteryPreferenc.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done
