### ISSUE TITLE
Sub form should not show on taskbar

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#129]
Sub form should not show on taskbar

**Comment by VIRAG-RestAlgo** [comment]
@Anil-Restalgo  please check and update.

**Comment by Sakshi-Restalgo** [comment]
Development done

**Comment by VIRAG-RestAlgo** [comment]
@Sakshi-Restalgo    send me Check point.

**Comment by Sakshi-Restalgo** [comment]
below is my  T129 checkpoint please check and review that

[CheckPoint-ShowInTaskBarAllForms.pdf](https://github.com/user-attachments/files/15603627/CheckPoint-ShowInTaskBarAllForms.pdf)
