### ISSUE TITLE
Normal market watch - expire token  replace with new token

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#138]
In normal market watch, if yesterday saved token expire today and token property BN-47000-CE-NSEFO then in new day with this property get new token and add in watch and saved.

![Image](https://github.com/RestAlgo/TradingApplication/assets/168618063/fc260d1d-9ef7-46f6-909a-83105b68eaa5)

**Comment by Kartik-RestAlgo** [comment]
token format change from "NSEFO-48199" TO "NSEFO-OPTIDX-BANKNIFTY-CE-43100" in frmCreateWatch
save and Load completed.
for F5 new token added in market in new formate

**Comment by Kartik-RestAlgo** [comment]
Token also Add in create watch from F7 and F9 in new token format
and also save and load token

**Comment by Kartik-RestAlgo** [comment]
this task Started on 03-06-2024 on 09:00 AM

New form of F7 merger with current branch KAR_T138
also check frmMarketDepth, frmAddToScript and and frmSnapQuote.
from all form new token will add and load in create MarketWatch
and also required code Separated and also Testing by Me .
Testing Pending by Virag sir

**Comment by VIRAG-RestAlgo** [comment]
@Kartik-RestAlgo this task will merge in this week if possible.

**Comment by VIRAG-RestAlgo** [comment]
@Kartik-RestAlgo  please attached pdf file.

**Comment by Kartik-RestAlgo** [comment]
[Expire token replace with new token_T138.pdf](https://github.com/user-attachments/files/16466507/Expire.token.replace.with.new.token_T138.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done and Tested in live in 2nd Aug 2024
