### ISSUE TITLE
Market depth form should be single ton

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#141]
Only single form open on screen of market depth.

if user press F5 from any token and market depth already open then refresh data as per new token.

**Comment by Usha-Restalgo** [comment]
singtone object is created and tested by me 
testing by Virag sir is remian so putting this task in devlopment done

**Comment by VIRAG-RestAlgo** [comment]
Market depth form will open from,

- Normal market watch
- Order Book
- Trade Book
- Net position
- Rule wise net position.

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo   send me Check point.

**Comment by Usha-Restalgo** [comment]
[141-MarketDepth SingleTone.pdf](https://github.com/user-attachments/files/16409046/141-MarketDepth.SingleTone.pdf)
