### ISSUE TITLE
In OrderBook On Right Click Add Menu Of CancellAll

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#142]
In FrmOrderBookList's ReportGrid RightClick Then Menu Add of CancelAll in this task do to In OrderBook All Pending Order Cancel By Click On Cancel All.

If Any Help Ask To @Anil-Restalgo .

**Comment by VIRAG-RestAlgo** [comment]
1st ->  Get all pending orders from main memory (Status "Pending") add in new list<orderbookrow>
2nd ->new list<orderbookrow> run foreach loop.
3rd -> in foreach loop again check status by OrderUniqueID
4th -> If latest status is PENDING then send order to cancel.

**Comment by Sakshi-Restalgo** [comment]
Devlopment Done For FrmOrderBookList's ReportGrid RightClick Then Menu Add of CancelAll in this task do to In OrderBook All Pending Order Cancel By Click On Cancel All.

[CheckPoint_CancelAll.pdf](https://github.com/RestAlgo/TradingApplication/files/15497267/CheckPoint_CancelAll.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done
