### ISSUE TITLE
Send receive master file (Index token master and bhavcopy)

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#143]
We need to send request of master file Index token and bhavcopy and load in trading system main memory.

Contract master file + two new file (Index token master + bhavcopy)

This task you have to run in latest trading version.

If you have any query you can ask to @Anil-Restalgo

**Comment by Sakshi-Restalgo** [comment]
Development Done

**Comment by VIRAG-RestAlgo** [comment]
Send Me checkpoint @Sakshi-Restalgo

**Comment by VIRAG-RestAlgo** [comment]
Done

**Comment by Sakshi-Restalgo** [comment]
below is my  T143 checkpoint please check and review that

[CheckPoint_FileDownloadingList.pdf](https://github.com/user-attachments/files/15604138/CheckPoint_FileDownloadingList.pdf)
