### ISSUE TITLE
New Strategy : ConversionReversal Add Rule.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#145]
1. Add new strategy name in strategy combo as "ConRev".
2. Minimum and Maximum 3 leg can add
3. Leg selection combo disable
4. 2nd leg always disable
5. On changes 1st leg Option type change in 2nd leg. if 1st leg CE then 2nd leg PE. and if 1st leg PE then 2nd leg CE, on changes on 1st leg automatically change 2nd option type.
6. Remaining all leg details same.
7. if change any leg details in 1st leg that automatically reflect in 2nd leg with same data.
8. Ratio always 1 in all 3 leg. & disable ratio box
9. Step + and - and Price diff will be apply in on 1st and 2nd leg.

we have video recording for ready ref.

**Comment by Usha-Restalgo** [comment]
Add new strategy name in strategy combo as "ConRev".
Minimum and Maximum 3 leg can add
Leg selection combo disable
2nd leg always disable
On changes 1st leg Option type change in 2nd leg. if 1st leg CE then 2nd leg PE. and if 1st leg PE then 2nd leg CE, on changes on 1st leg automatically change 2nd option type.
Remaining all leg details same.
if change any leg details in 1st leg that automatically reflect in 2nd leg with same data.
Ratio always 1 in all 3 leg. & disable ratio box  -This task are done

**Comment by Usha-Restalgo** [comment]
Step + and - and Price diff will be apply in on 1st and 2nd leg. -development done 
Testing done by UPM 
So putting this task to development done

**Comment by Usha-Restalgo** [comment]
attaching a pdf of this task

[145-ConRev Rule.pdf](https://github.com/user-attachments/files/15542595/145-ConRev.Rule.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done.
