### ISSUE TITLE
Change to Report Grid in UserMasterList form

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#146]
Change data grid view of UserMsater List form to ReportGrid.

* Create all columns of User Master (Common Tab) in grid columns for column profile.
* Remove Edit and Delete buttons from the grid and add option to edit or delete from context menu.

**Comment by Sakshi-Restalgo** [comment]
Development Done and Testing Pending With Aman Bhai

**Comment by Aman-Restalgo** [comment]
Testing Done by My side 
tested by ppb  and  Merged with ppb

**Comment by Sakshi-Restalgo** [comment]
below is my T146 checkpoint please check and review that
[CheckPoint - AdminModule.pdf](https://github.com/user-attachments/files/16156488/CheckPoint.-.AdminModule.pdf)
