### ISSUE TITLE
C-R Strategy develop and show

### ISSUE THREAD

**Issue by dhruvin-restalgo** [RestAlgo/TradingApplication#152]
Show Spread of Fs & Rs for Conversal reversal strategy in strategy Window

Domain - Vaibhav Shah

**Comment by VIRAG-RestAlgo** [comment]
Development done.
Testing done in recording.
tomorrow testing in live.

**Comment by VIRAG-RestAlgo** [comment]
Live Testing done with client on dated 04 June 2024.
