### ISSUE TITLE
Open buy sell form from trade book and NetPosition.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#156]
Merge from Trading System Task No 41 in TradingSystem.

**Comment by Kartik-RestAlgo** [comment]
frmorderBookList, frmTradebookList, frmNetPositionList Form and related classes also merge in Admine module from Trading System

**Comment by pratik-restalgo** [comment]
Done

**Comment by Kartik-RestAlgo** [comment]
This task handle in T491

[Add Strategy Name filter in Net Position_T491.pdf](https://github.com/user-attachments/files/17111494/Add.Strategy.Name.filter.in.Net.Position_T491.pdf)

**Comment by pratik-restalgo** [comment]
done
