### ISSUE TITLE
Remove Branch Map in user master

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#158]
* Remove branch map tab from user master.
* Remove dependency of branch map from client map and dealer map tab in DP SP.

**Comment by Aman-Restalgo** [comment]
Task is done.

[T_158_CheckPoint_AdminModule_10-06-2024.pdf](https://github.com/user-attachments/files/15758279/T_158_CheckPoint_AdminModule_10-06-2024.pdf)

**Comment by pratik-restalgo** [comment]
Done
