### ISSUE TITLE
Trade file export from tradebook - NSEFO

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#159]
Logic should be in Interface and manger method.

1. Make model as per file header. (Model Name ExportTradeBookModel)
2. Make a list of new model and add all rows from tradebook to new model list.
3.  Validation : Exchange Should be **NSEFO**
4. Get Data from tradebook and set in new model.
5. export in Csv.
6. File Name [TradeBook_{LoginName_DateTime.Now].csv

[Trade File Format - FO.xlsx](https://github.com/user-attachments/files/15746534/Trade.File.Format.-.FO.xlsx)

**Comment by Sakshi-Restalgo** [comment]
devlopment done for Trade file export from tradebook 
testing pending with virag sir

**Comment by Sakshi-Restalgo** [comment]
devlopment done for Trade file export from tradebook csv file
Testing done for my side

**Comment by lokesh-rydt** [comment]
Merging is not required, duplicate task with #6
