### ISSUE TITLE
Failed order message display in Admin Module

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#169]
Display old failed order messages in failed window in admin module when login.
1. Save failed order list to binary file periodically.
2. Load saved failed orders list from binary file when Admin login successfully.
3. Request for failed orders messages to RYDT Ops Engine with last login tick.
4. Receive failed orders messages from RYDT Ops Engine and fill list.

**Comment by Kartik-RestAlgo** [comment]
The following two tasks have been completed:

1. Save failed order list to binary file periodically.
2. Load saved failed orders list from binary file when Admin login successfully.

**Comment by Kartik-RestAlgo** [comment]
it is Done on 14-June-2024
