### ISSUE TITLE
T000014: Index Average

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#17]
1. Load Index Master
2. Update CE token and PE Token for selected index for nearest strike price hourly.
3. Avg Price, Avg Tick, Avg Total, Sy.Price, Sy. Total, Sy.Tick, Sy Avg. set to 0 hourly.
4. Point no 2 and 3 should not work after 3.00 PM.

**Comment by VIRAG-RestAlgo** [comment]
Separate exe is already running.

**Comment by VIRAG-RestAlgo** [comment]
@Kartik-RestAlgo  send me Check point.

**Comment by Kartik-RestAlgo** [comment]
[IndexAverage_T17.pdf](https://github.com/user-attachments/files/15603277/IndexAverage_T17.pdf)
