### ISSUE TITLE
Validation for branch delete

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#170]
Branch cannot be deleted when the branch is mapped as parent branch for any other client/dealer/branch.

**Comment by Aman-Restalgo** [comment]
This task is Done and i am create a new UserMasterListManager and code segregate and manage

**Comment by Aman-Restalgo** [comment]
[T_170_CheckPoint_AdminModule_16-07-2024.pdf](https://github.com/user-attachments/files/16244127/T_170_CheckPoint_AdminModule_16-07-2024.pdf)

**Comment by pratik-restalgo** [comment]
done
