### ISSUE TITLE
RYDT Config File Code merge

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#172]
As per new concept given by lokeshsir you have already code, that code only merge in trading application with updated dll.

**Comment by Usha-Restalgo** [comment]
development done

**Comment by Usha-Restalgo** [comment]
below is checkpoint of frmconfig manager 


[FrmConfigManagerCheckPoiint.pdf](https://github.com/user-attachments/files/15765974/FrmConfigManagerCheckPoiint.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done in trading application.
