### ISSUE TITLE
NetValue in netposition if + then show in blue color or - then show in red color.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#181]
NetValue in netposition if + then show in blue color or - then show in red color.

**Comment by Usha-Restalgo** [comment]
added new method to cellvalueneeded to perfrom this task 
so moving this task to devlopment done and testing by VMD is remain

**Comment by Usha-Restalgo** [comment]
as discussed with vaibhav sir we have to change the value of M2M total cell color
and not netvalue so change the code according to that

**Comment by Usha-Restalgo** [comment]
Below is my this task checkpoint


[181NetValue in netposition if + then show in blue color or - then show in red color.pdf](https://github.com/user-attachments/files/15880918/181NetValue.in.netposition.if.%2B.then.show.in.blue.color.or.-.then.show.in.red.color.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done.
