### ISSUE TITLE
In Algo marketwatch, if any rule update then show popup message on screen.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#184]
In Algo marketwatch, if any rule update then show popup message on screen.

Before start this task 1st need to discuss with Vaibhavbhai then Lokeshsir.

**Comment by Usha-Restalgo** [comment]
devloped in 15 min forget to add in devlopment done

**Comment by VIRAG-RestAlgo** [comment]
Send back to in process.

as per testing today.

**Comment by VIRAG-RestAlgo** [comment]
Issue face on time code check and merged

1. make responsible method.
2. clean rule, F1-F2 changes popup message not sho.

**Comment by Usha-Restalgo** [comment]
make responsible method.-done
clean rule, F1-F2 changes popup message not showing.-done
also add this method when user active and deactive  rule
testing by vmd is remains so putting this task to development done

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo add pdf and check logic today or tomorrow,.

**Comment by Usha-Restalgo** [comment]
[184-Algomarketwatch show popup message.pdf](https://github.com/user-attachments/files/16408583/184-Algomarketwatch.show.popup.message.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done and updated in live
