### ISSUE TITLE
Netposition column ascending - descending  features need to added.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#190]
Netposition column ascending - descending  features need to added.

In this task need to test performance also with minimum 50 tokens.

**This task need to merge in admin also**

**Comment by pratik-restalgo** [comment]
Done.

**Comment by Kartik-RestAlgo** [comment]
This task is Merged in T325 

[Use LINQ to add filtering in Net Position_T325.pdf](https://github.com/user-attachments/files/17111119/Use.LINQ.to.add.filtering.in.Net.Position_T325.pdf)
