### ISSUE TITLE
Netposition column ascending - descending features need to added.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#192]
Merge from Trading system Task no 190

**Comment by pratik-restalgo** [comment]
Please add checkpoint.

**Comment by Kartik-RestAlgo** [comment]
This Task is handle in #T491

[Add Strategy Name filter in Net Position_T491.pdf](https://github.com/user-attachments/files/17111330/Add.Strategy.Name.filter.in.Net.Position_T491.pdf)
