### ISSUE TITLE
Create manager class for User Master Add/Edit form

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#214]
Create manager class for User Master Add/Edit form

**Comment by Aman-Restalgo** [comment]
working don on 15-06-2024 16:00pm

**Comment by Aman-Restalgo** [comment]
[T_214_CheckPoint_AdminModule_16-07-2024.pdf](https://github.com/user-attachments/files/16244135/T_214_CheckPoint_AdminModule_16-07-2024.pdf)

**Comment by pratik-restalgo** [comment]
done
