### ISSUE TITLE
Add Limit Master single form for All Client, All Dealer, All Branch.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#23]
If individual limit master added for any client, any dealer and any branch then check only individual only.

![Image](https://github.com/RestAlgo/TradingApplication/assets/168447176/2e6fffb9-28c5-442f-b970-b9e6fdd1b03e)

**Comment by Aman-Restalgo** [comment]
I am halping  usha mam and sakshi mam on 16:10 to 16:52

**Comment by Aman-Restalgo** [comment]
healping usha mam

**Comment by Aman-Restalgo** [comment]
"I have done as much as I understood from what you explained. For further assistance, I will need to talk to PPB sir."

**Comment by VIRAG-RestAlgo** [comment]
@Aman-Restalgo   send me Check point.

**Comment by Aman-Restalgo** [comment]
Checkpoint

[T_23_CheckPoint_RYDTEngine_10-06-2024.pdf](https://github.com/user-attachments/files/15756784/T_23_CheckPoint_RYDTEngine_10-06-2024.pdf)
