### ISSUE TITLE
Clean rule issue as per live testing on date 14-06-2024

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#235]
Clean rule issue as per live testing on date 14-06-2024,

Clean rule issue while re active rule, forward cycle not clean.

**Comment by VIRAG-RestAlgo** [comment]
Kindly insert log for clean rule also.

**Comment by Usha-Restalgo** [comment]
This task error is caught and solved so putting this task to devlopment done
