### ISSUE TITLE
when deactivating rule it taking time

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#238]
when deactivating rule it taking time

**Comment by Usha-Restalgo** [comment]
just refresh datagridview to achive this task 
This task is done on 15-06-2024
So putting this task in Development done

**Comment by VIRAG-RestAlgo** [comment]
@Anil-Restalgo please explain case to us so we can merge this code other wise this is not required to merge.

Right now I am close this task with out merge.

@Usha-Restalgo This code is not required to merge.
