### ISSUE TITLE
DPR value 0.05 - 15.50, if price enter 0.05 or 15.50 then low message should not be show

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#239]
DPR value 0.05 - 15.50, if price enter 0.05 or 15.50 then low message should not be show

**Comment by Usha-Restalgo** [comment]
just have to change condition in validation file of normal sell and normal buy to achieve this task
This task is done on 15-06-2024
So putting this task in development done

**Comment by VIRAG-RestAlgo** [comment]
Done
