### ISSUE TITLE
Order lot and Net lot for FS and RS change from grid then ask Do you want to update Qty? YesNo.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#24]

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo    send me Check point.

**Comment by Usha-Restalgo** [comment]
below is my checkpoint for taskno.24
Please read and review that


[Taskono.24 Checkpoint.pdf](https://github.com/user-attachments/files/15604071/Taskono.24.Checkpoint.pdf)

**Comment by VIRAG-RestAlgo** [comment]
This point is face in live testing in Pronto application. (This is pending to merge by VMD)

**Comment by VIRAG-RestAlgo** [comment]
as per today testing, send back to in process

**Comment by VIRAG-RestAlgo** [comment]
Issue face on time code check and merged

1. one time ask do you want to update qty? if rule active instead off two times.
2. Responsible method
3. Net Lot issue while exe.lot available (For Ex. FEx.Lot 5 and NetLot need to write 5 then not show proper message while rule is deactive mode)
4. As per point no 3 ordering issue while re active.
5. Order lot should not be bigger then net lot.
6. Give comment which code is changed.

**Comment by Usha-Restalgo** [comment]
one time ask do you want to update qty? if rule active instead off two times.-done
Net Lot issue while exe.lot available (For Ex. FEx.Lot 5 and NetLot need to write 5 then not show proper message while rule is deactive mode)-done
As per point no 3 ordering issue while re active.-done
Order lot should not be bigger then net lot.-done
Responsible method-done
changes in isvalidgriddata,added new method IsValidOrderDetail,CheckFexcutelotwithNetLotForF1,CheckRexcutelotwithNetLotForF2

**Comment by Usha-Restalgo** [comment]
testing from vmd is remian so putting this task to devlopment done

**Comment by VIRAG-RestAlgo** [comment]
Not proper work please check again.

**Comment by Usha-Restalgo** [comment]
[24-FsRsLogic1.pdf](https://github.com/user-attachments/files/16455823/24-FsRsLogic1.pdf)

Revise checkpoint of task no 24

**Comment by VIRAG-RestAlgo** [comment]
Done and test with Dipakbhai and he says Ok. @Jill-Restalgo  please confirm again.
