### ISSUE TITLE
Order book open from market depth.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#240]

**Comment by VIRAG-RestAlgo** [comment]
Order book open from market depth (token pending)

**Comment by Usha-Restalgo** [comment]
Task is done 
task is done in 10 to 15 minutes but forget to put task in development done

**Comment by Usha-Restalgo** [comment]
below is my checkpoint for this task


[240Order book open from market depth..pdf](https://github.com/user-attachments/files/15880839/240Order.book.open.from.market.depth.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done.
