### ISSUE TITLE
Application style config (dockable)

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#247]
1. Default config make and store in file.
2. 1st time if new user login then Default config load and show.
3. User wise config store in that folder and load from that folder.

**Comment by Usha-Restalgo** [comment]
Task is done from my side so putting this task into development done 
Testing By Virag sir is remain

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo right now i am thinking about this task,

Can we divert all logic from main to manager.

We will try and see which type of issues getting.

1st copy the main form and try on it.

Tomorrow i will explain in detail.

Please move this task to In process or To Do.

**Comment by Usha-Restalgo** [comment]
As per discussion this task is done
so putting this task to development done

**Comment by VIRAG-RestAlgo** [comment]
merged in live branch.

**Comment by Usha-Restalgo** [comment]
[247-appkicationFileConfig.pdf](https://github.com/user-attachments/files/16410386/247-appkicationFileConfig.pdf)
