### ISSUE TITLE
in all grid row hight can't be change by user.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#25]

**Comment by Anil-Restalgo** [comment]
Put in In Progress Because in  MarketWatch Form Not Work This.

**Comment by Anil-Restalgo** [comment]
[T25 in all grid row hight can't be change by user..pdf](https://github.com/user-attachments/files/15787719/T25.in.all.grid.row.hight.can.t.be.change.by.user.pdf)

**Comment by Anil-Restalgo** [comment]
Done

**Comment by Anil-Restalgo** [comment]
@pratik-restalgo  For Your Information only Add in frmCreateWatch and All Other Form Done With This Point.
