### ISSUE TITLE
Maintain order history in Admin Module in binary file

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#264]
Maintain order history in Admin Module in binary file same as in Trading System.

**Comment by Kartik-RestAlgo** [comment]
Order history in Admin Module save in binary file save same as Trading System.

**Comment by pratik-restalgo** [comment]
add check point.

**Comment by Kartik-RestAlgo** [comment]
[Get Order History from RYDT Ops Engine_T355.pdf](https://github.com/user-attachments/files/17111326/Get.Order.History.from.RYDT.Ops.Engine_T355.pdf)
