### ISSUE TITLE
Handle Order Entry Preference

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#268]
Buy Product: Assign selected item from this combo to Product type combo on Normal Buy form.
Sell Product: Assign selected item from this combo to Product type combo on Normal Sell form.
Value Alert: Alert if order value is more then assigned in Value Alert textbox and ask "Order value is more then {Value Alert textbox.text} Do you want to order?" with "Yes" and "No" buttons.
			 If Avert check box beside Value Alert textbox is checked then focus on "No" button in messagebox dialog box.
			 If the check box is not checked then focus on "Yes" button.

Price Alert %:
			* For buy orders, If order value is more then price alert % from LTP then ask "Order value is more then {Price Alert textbox.text} Do you want to order?" with "Yes" and "No" buttons.
			  If Avert check box beside Price Alert % textbox is checked then focus on "No" button in messagebox dialog box.
			  If the check box is not checked then focus on "Yes" button.
			* For sell orders, If order value is less then price alert % from LTP then ask "Order value is more then {Price Alert textbox.text} Do you want to order?" with "Yes" and "No" buttons.
			  If Avert check box beside Price Alert % textbox is checked then focus on "No" button in messagebox dialog box.
			  If the check box is not checked then focus on "Yes" button.

Qty/Lots Alert:
			* For FO: Convert order qty to lots and if Order Qty Lots are more then alert qty then ask "Order qty is more then {Qty Alert textbox.text} Do you want to order?" with "Yes" and "No" buttons.
			  If Avert check box beside Price Alert % textbox is checked then focus on "No" button in messagebox dialog box.
			  If the check box is not checked then focus on "Yes" button.
			* For CM: If Order Qty is more then alert qty then ask "Order qty is more then {Qty Alert textbox.text} Do you want to order?" with "Yes" and "No" buttons.
			  If Avert check box beside Price Alert % textbox is checked then focus on "No" button in messagebox dialog box.
			  If the check box is not checked then focus on "Yes" button.

MPP%: Development is done, testing need to be done for market order. (Check calculation in normal buy and normal sell forms.)

Confirm Orders:
	* New: If checked then ask "Do you want to submit order?" for every NEW orders.
	* Mod: If checked then ask "Do you want to submit order?" for every MODIFIED orders.
	* Cancel: If checked then ask "Do you want to cancel order?" every time when order is canceled.
	* Price Stop on new orders: If checked by default focus on price textbox on normal order buy/sell forms for NEW orders only.
	* Price Stop on mod: If checked by default focus on price textbox on normal order buy/sell forms for MODIFIED orders only.
	* Hide Client Prefix check box.
	* Split Qty: Separate new task.

**Comment by Usha-Restalgo** [comment]
this task is done so putting this task to development done

**Comment by Usha-Restalgo** [comment]
[329-OrderPrefnrece.pdf](https://github.com/user-attachments/files/16373890/329-OrderPrefnrece.pdf)
