### ISSUE TITLE
Save button should be added

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#27]

**Comment by VIRAG-RestAlgo** [comment]
Done. 

Click on File & View -> WorkSpace save

**Comment by Jill-Restalgo** [comment]
ok!!

Thanks and Regards,

Name: Ms. Jill Sheth
Position: Desktop Support
Company Name:  Restalgo Tech Private Limited
Address: 1008-10,  Akik Tower Near Pakwan Restaurant
                      Bodakdev,Ahmedabad-380054
Email ID: ***@***.***
Website:  https://restalgo.com/



________________________________

**Comment by Jill-Restalgo** [comment]
ok!

Thanks and Regards,

Name: Ms. Jill Sheth
Position: Desktop Support
Company Name:  Restalgo Tech Private Limited
Address: 1008-10,  Akik Tower Near Pakwan Restaurant
                      Bodakdev,Ahmedabad-380054
Email ID: ***@***.***
Website:  https://restalgo.com/



________________________________
