### ISSUE TITLE
Auto Slicing

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#279]
If "Split Qty If Beyond Freez Qty" is checked in order entry preferences then,
1. Check for freez qty from base symbol wise dictionary received from engine.
2. If Order Qty is more then freez qty then ask "Do you want to split the order?"
3. If "Yes" then split the order in multiply to freez qty. All the order related validations should be checked for order before every order.
4. If "No" then do not send any order.

Auto slicing calculation:
Freez Qty = 100
Order Qty = 1000
Total Order = 1000/100 = 10
Order Qty in each order = 100

**Comment by Aman-Restalgo** [comment]
This task is Done

[T279CheckPoint_TredingSystem_24-07-2024.pdf](https://github.com/user-attachments/files/16362940/T279CheckPoint_TredingSystem_24-07-2024.pdf)
