### ISSUE TITLE
FExLot and RExLot not getting proper in grid

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#28]

**Comment by dhruvin-restalgo** [comment]
Update?

**Comment by VIRAG-RestAlgo** [comment]
As discussed today with Vaibhavbhai and Lokeshsir attached sheet update logic.

[Execute Lot.xlsx](https://github.com/user-attachments/files/15766101/Execute.Lot.xlsx)

**Comment by VIRAG-RestAlgo** [comment]
As discussed with Vaibhavbhai this is Done.
