### ISSUE TITLE
Change date format for xmitted order in Order Book

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#282]
date format for xmitted orders displayed with "/" separator.  It should be uniform as other orders.

**Comment by Usha-Restalgo** [comment]
Devlopment done

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo  Add pdf file

**Comment by Usha-Restalgo** [comment]
[282-Change DateFormate.pdf](https://github.com/user-attachments/files/16375636/282-Change.DateFormate.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done
