### ISSUE TITLE
Delete Template in Algo Rule

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#284]
Add option to delete template in Algo Rule form.

@VIRAG-RestAlgo Please, add details.

**Comment by Usha-Restalgo** [comment]
Devlopment done

**Comment by Usha-Restalgo** [comment]
below is my checkpoint

[284-delete template in algo rule.pdf](https://github.com/user-attachments/files/16518785/284-delete.template.in.algo.rule.pdf)

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo and @Aman-Restalgo update this task in New Algo Rule form.
This task move to TODO

**Comment by VIRAG-RestAlgo** [comment]
@Aman-Restalgo need to apply in new algo rule form.

**Comment by Aman-Restalgo** [comment]
done this task 07-10-2024

**Comment by VIRAG-RestAlgo** [comment]
Done by VMD in new logic. and deploy now.
