### ISSUE TITLE
Token Subscribe Manager

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#286]
Create Common Global Dictionary for Token To be subscribe by creating SubscriptonManager

Add function to Subscribe, Unsubscribe, Load and Save

Option to add token from MW, RW, Depth etc... means anywhere when any token needs to subscribe

In Future, there will be some license logic to restrict the number of token subscribe

**Comment by Anil-Restalgo** [comment]
Hold Because Discussion Pending With @VIRAG-RestAlgo

**Comment by VIRAG-RestAlgo** [comment]
This point is cover in #514 by VMD.
