### ISSUE TITLE
Create new form for User Master

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#295]
Create new form for User Master:

Display logged in user's details and mapped client's details in the data grid view.
Fields to display:

1. ID
2. Name
3. PAN

[USER.json](https://github.com/user-attachments/files/16038791/USER.json)

**Comment by Aman-Restalgo** [comment]
I started this task in the morning, but I didn't put it in progress until the afternoon, and now the task is complete.

**Comment by Aman-Restalgo** [comment]
[T_295&296_CheckPoint_AdminModule_24-07-2024.pdf](https://github.com/user-attachments/files/16358006/T_295.296_CheckPoint_AdminModule_24-07-2024.pdf)

**Comment by Aman-Restalgo** [comment]
Some update in this task that's why  we get in Progress

**Comment by Aman-Restalgo** [comment]
this task because of i need some data get in trading system from engine

**Comment by pratik-restalgo** [comment]
This task is covered in #296
