### ISSUE TITLE
Market depth(F5) should open on every window as it is itself a different window.

### ISSUE THREAD

**Issue by Info-Restalgo** [RestAlgo/TradingApplication#301]

**Comment by VIRAG-RestAlgo** [comment]
As discussed with Lokeshsir please make decision table first then development start

**Comment by lokesh-rydt** [comment]
@Anil-Restalgo 
Please prepare all contingency and make Decision Table before developmenet

**Comment by Anil-Restalgo** [comment]
[Decision Table (MarketDepth).xlsx](https://github.com/user-attachments/files/16386843/Decision.Table.MarketDepth.xlsx)

**Comment by Anil-Restalgo** [comment]
[T301 Market depth(F5) should open on every window as it is itself a different window..pdf](https://github.com/user-attachments/files/16391341/T301.Market.depth.F5.should.open.on.every.window.as.it.is.itself.a.different.window.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done

**Comment by Jill-Restalgo** [comment]
In FUTIDX and FUTSTK F1/F2 not working properly. 
In both pronto and Nx-block.
@VIRAG-RestAlgo @pratik-restalgo
