### ISSUE TITLE
Strategy wise algo legs control

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#305]
Strategy wise algo legs control

**Comment by Usha-Restalgo** [comment]
forget to put task inprogress work start at 9.30
and compelted at 15:30
do putting thistask to task done
test by vmd is pending

**Comment by VIRAG-RestAlgo** [comment]
We need strategy wise control

**Comment by Usha-Restalgo** [comment]
task no 24 is currently running so putting this task to TODO

**Comment by Usha-Restalgo** [comment]
this task is devlopment done 
test by vmd is remain

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo  this task  will check and merge when we merged Task ID 345

**Comment by Usha-Restalgo** [comment]
[305-StrategywiseAlgoLegsControl.pdf](https://github.com/user-attachments/files/16408737/305-StrategywiseAlgoLegsControl.pdf)

**Comment by VIRAG-RestAlgo** [comment]
This task move to done due to TaskID #482 create and WIP now.
