### ISSUE TITLE
Index View and Index Average Changes

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#307]
**Index View**

1. Percentage % column header proper.
2. This form should not be close on escape.
3. Dockable facility removed.
4. Right click to add token option.
5. Token search by indices name.
6.  Red blue for color should be highlight as per MarketWatch (this point with VMD)

**Index Average**

1. Add token by right click.
2. New token add by F5

**Trading System**

1. If application by close button then ask message "Do you want to exit ?" and focus on "No" option.
2. In title bar show USERID instead of User Name.

**Comment by Anil-Restalgo** [comment]
Done All Point Only Remaining 
Point No 6.
Red blue for color should be highlight as per MarketWatch (this point with VMD)
this Point Doing with VMD.

**Comment by VIRAG-RestAlgo** [comment]
Sr. No 6 is done.

**Comment by VIRAG-RestAlgo** [comment]
This task in between hold due to other urgent work in hand of APN.

**Comment by Anil-Restalgo** [comment]
[TaskID.307 Index View and Index Average Changes.pdf](https://github.com/user-attachments/files/16455246/TaskID.307.Index.View.and.Index.Average.Changes.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done and merge in live exe.
