### ISSUE TITLE
Add NSECM token in Market Watch from token selector

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#308]
Add NSECM token in Market Watch from token selector.

**Comment by Kartik-RestAlgo** [comment]
Security text file add to script master list and Tokens are added in market watch.

**Comment by Kartik-RestAlgo** [comment]
[Add NSECM token in Market Watch from token selector_T308.pdf](https://github.com/user-attachments/files/17107855/Add.NSECM.token.in.Market.Watch.from.token.selector_T308.pdf)

**Comment by pratik-restalgo** [comment]
Done
