### ISSUE TITLE
Only "Branch" can login in Admin Module

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#311]
In Admin module, add validation that only "Branch" can login. If other then "Branch" user try to connect, display message "This user cannot login.".

**Comment by Kartik-RestAlgo** [comment]
Only Branch can login from Admin Module.

**Comment by Kartik-RestAlgo** [comment]
[Only Branch can login in Admin Module_T311.pdf](https://github.com/user-attachments/files/16490820/Only.Branch.can.login.in.Admin.Module_T311.pdf)

**Comment by pratik-restalgo** [comment]
done
