### ISSUE TITLE
Add UserTypeCode filter in UserMasterList form

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#317]
Add UserTypeCode filter in UserMasterList form

**Comment by Aman-Restalgo** [comment]
I am Start this task at 11:25 and this time done this task

**Comment by Aman-Restalgo** [comment]
[T_317_CheckPoint_AdminModule_16-07-2024.pdf](https://github.com/user-attachments/files/16243974/T_317_CheckPoint_AdminModule_16-07-2024.pdf)

**Comment by pratik-restalgo** [comment]
done
