### ISSUE TITLE
Display branch, dealer and clients only assigned to logged in branch and child branch

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#318]
In User Master List form, display branch, dealer and client who's parent branch is logged in branch or logged in branch's child branch.

(i.e.) B1 Branch is parent branch of B1A and B1B and D1 and D2 dealers and C1 and C2 clients are in B1A branch and D3 and D4 dealers and C3 and C4 clients are in B1B branch.
If B1 branch is logging in Admin Module then all branches (B1A, B1B), all Dealers (D1, D2, D3, D4) and all clients (C1, C2, C3, C4) will be displayed in the list.
If B1A branch is logging in Admin Module then D1 and D2 dealers and C1 and C2 dealers only will be displayed in the list.
If B1B branch is logging in Admin Module then D2 and D3 dealers and C2 and C3 dealers only will be displayed in the list.

**Comment by Aman-Restalgo** [comment]
working on task number 278

**Comment by Aman-Restalgo** [comment]
test sakshi mams code

**Comment by Aman-Restalgo** [comment]
i am working this task on 11 am to 6 pm

**Comment by Aman-Restalgo** [comment]
this task don yesterday but pending discuss with lokesh sir

**Comment by Aman-Restalgo** [comment]
Done by lokesh sir

**Comment by Aman-Restalgo** [comment]
testing and merging a code old branch to new branch

**Comment by Aman-Restalgo** [comment]
merging a code old branch to new branch and testing done  merging pending

[T_318&319_CheckPoint_AdminModule_24-07-2024.pdf](https://github.com/user-attachments/files/16357967/T_318.319_CheckPoint_AdminModule_24-07-2024.pdf)

**Comment by pratik-restalgo** [comment]
done
