### ISSUE TITLE
Use LINQ to add filtering in Net Position.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#325]
Generate dummy orders for 5 tokens and 10000 orders per seconds.
and use LINQ to filter to generate net position.

**Comment by Kartik-RestAlgo** [comment]
Add New Linq to Filter in Net Position.

**Comment by Kartik-RestAlgo** [comment]
unreliazeM2M is not correct so change Method And logic for the same

**Comment by Kartik-RestAlgo** [comment]
[Use LINQ to add filtering in Net Position_T325.pdf](https://github.com/user-attachments/files/17111075/Use.LINQ.to.add.filtering.in.Net.Position_T325.pdf)
