### ISSUE TITLE
RuleNo

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#328]
While create rule at that time rule no assing value userid_tick(5)_rulesrno.

**Comment by Usha-Restalgo** [comment]
devlopment done

**Comment by VIRAG-RestAlgo** [comment]
Done and updated in master branch.

**Comment by Usha-Restalgo** [comment]
[328-RuleNo.pdf](https://github.com/user-attachments/files/16410575/328-RuleNo.pdf)
