### ISSUE TITLE
K, L, C, M, set in AdHoc grid in Limit Master and Template Master

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#341]
K, L, C, M, set in AdHoc grid in Limit Master and Template Master

**Comment by Aman-Restalgo** [comment]
this task done before create task

**Comment by Aman-Restalgo** [comment]
[T_341_CheckPoint_AdminModule_19-07-2024.pdf](https://github.com/user-attachments/files/16302675/T_341_CheckPoint_AdminModule_19-07-2024.pdf)

**Comment by pratik-restalgo** [comment]
done
