### ISSUE TITLE
Number of branch license validation

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#343]
Add new validation in user master to create only allowed number of branches validate from license file.

**Comment by Aman-Restalgo** [comment]
hold because of testing 349 no task

**Comment by Aman-Restalgo** [comment]
this task is done

[T343_CheckPoint_AdminModule_24-07-2024.pdf](https://github.com/user-attachments/files/16357946/T343_CheckPoint_AdminModule_24-07-2024.pdf)

**Comment by pratik-restalgo** [comment]
Done.
