### ISSUE TITLE
Add rule form re structure due to maintain many strategy

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#345]
Add rule form re structure due to maintain many strategy.

Strategy wise template name show and load.

Strategy wise algo leg control add and show.

Strategy wise default template load.

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo add pdf and logic check this Saturday or next week.

**Comment by Usha-Restalgo** [comment]
[345-Restrucre Algo Rule.pdf](https://github.com/user-attachments/files/16408781/345-Restrucre.Algo.Rule.pdf)

**Comment by VIRAG-RestAlgo** [comment]
This task move to done due to TaskID #482 is WIP with @Usha-Restalgo and @Aman-Restalgo
