### ISSUE TITLE
Merge opening net position change from Trading System

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#347]
Merge opening net position change from Trading System

**Comment by Kartik-RestAlgo** [comment]
Merging Done

**Comment by Kartik-RestAlgo** [comment]
[Handle square off in Net Position_T347-T348.pdf](https://github.com/user-attachments/files/16490765/Handle.square.off.in.Net.Position_T347-T348.pdf)

**Comment by pratik-restalgo** [comment]
done
