### ISSUE TITLE
Handle square off in Net Position

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#348]
Handle square off in Net Position:
Fill below fields when send square off order from Admin:

LoginID = OrderBy from NetPositionRow
ClientCode = ClientCode from NetPositionRow

Display Client Code from NetPositionRow to NormalBuy/NormalSell forms and fill in order request packet from there.

As per explained by Vaibhavbhai on 19-07-2024, below order can be made from Admin Module:

If Order Qty is square off against opening qty and still admin place square off order then order should be placed. Means new order can be placed.

**Comment by pratik-restalgo** [comment]
Please add checkpoint.

**Comment by pratik-restalgo** [comment]
Done.

**Comment by Kartik-RestAlgo** [comment]
This task is handle in Task 491

[Add Strategy Name filter in Net Position_T491.pdf](https://github.com/user-attachments/files/17111509/Add.Strategy.Name.filter.in.Net.Position_T491.pdf)
