### ISSUE TITLE
Send lock/suspend user to RYDT Engine.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#349]
Send lock/suspend user id and Lock/Suspend flag in LockSuspendUser class to RYDT Engine in bytes

**Comment by Aman-Restalgo** [comment]
sakshi help and check support admin on 10 am

**Comment by Aman-Restalgo** [comment]
this task is done and related chenges in frmUserMasterAddEditPage

[T349_CheckPoint_AdminModule_24-07-2024.pdf](https://github.com/user-attachments/files/16357972/T349_CheckPoint_AdminModule_24-07-2024.pdf)

**Comment by pratik-restalgo** [comment]
Done.
