### ISSUE TITLE
Minimum lot size qty show in Qty field.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#350]
While we change any contract details at that time minimum lot size qty show in Qty field in normal buy and normal sell form.

**Comment by VIRAG-RestAlgo** [comment]
When you start this task please take development branch. (discuss)

**Comment by Usha-Restalgo** [comment]
this task is devloped in taskno329 brnach

**Comment by Usha-Restalgo** [comment]
devlopment is done 
Testing by Virag sir is pending
so moving this task to devlopment done

**Comment by VIRAG-RestAlgo** [comment]
Done and updated in live branch.

**Comment by Usha-Restalgo** [comment]
below is my checkpoint pdf

[350-Minimum lot size qty show in Qty field..pdf](https://github.com/user-attachments/files/16362408/350-Minimum.lot.size.qty.show.in.Qty.field.pdf)
