### ISSUE TITLE
Gset driver max lot

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#352]
If algowatch open and then Gsetproperty in max lot change then after after that can't update in memory properly.

Discuss while start this rule.

**Comment by Usha-Restalgo** [comment]
devlopment done

**Comment by Usha-Restalgo** [comment]
[352-Change ingset.pdf](https://github.com/user-attachments/files/16427279/352-Change.ingset.pdf)

this task is so small so this task is done in UPM_Fetures_T329_15072024 branch

**Comment by VIRAG-RestAlgo** [comment]
Done and merge in live exe
