### ISSUE TITLE
Notification Message Box repair

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#353]
Notification Message Box repair (re-structure) channel concept add

**Comment by Anil-Restalgo** [comment]
[T353 Notification Message Box repair..pdf](https://github.com/user-attachments/files/16400177/T353.Notification.Message.Box.repair.pdf)

**Comment by VIRAG-RestAlgo** [comment]
This point move to hold due to implement ch. managar

**Comment by VIRAG-RestAlgo** [comment]
This task is cover in #518 by VMD.
