### ISSUE TITLE
Add sorting in Net Position

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#358]
When click on header of any cell then order by that field from LINQ and update list with ordered records to display in virtual grid.

**Comment by VIRAG-RestAlgo** [comment]
@Kartik-RestAlgo  and @pratik-restalgo and @Sakshi-Restalgo  please check this point.

**Comment by Kartik-RestAlgo** [comment]
Issue in Continue Filtering

**Comment by pratik-restalgo** [comment]
Duplicate task with #190
