### ISSUE TITLE
Get order book/ trade book from RYDT Engine

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#361]
When login get Order Book/Trade Book after last login time and fill in respective list/dictionary.
Same thig is done in Trading System. In Trading system, it get only for logged in user. In Admin module, you have to get for all the user.

**Comment by Aman-Restalgo** [comment]
this task is done not issue in current Development

**Comment by pratik-restalgo** [comment]
Done.
