### ISSUE TITLE
Algo Rule Delete if any one leg expiry is passed.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#364]
Algo Rule Delete if any one leg expiry is passed.

**Comment by VIRAG-RestAlgo** [comment]
@Aman-Restalgo This task plan with Task ID 395

**Comment by Usha-Restalgo** [comment]
Development done 
Testing By VMD is remaining
so putting this task to development done

**Comment by Usha-Restalgo** [comment]
below is check point of this task
[364-Delte algo rule if expiry date is gone.pdf](https://github.com/user-attachments/files/17258021/364-Delte.algo.rule.if.expiry.date.is.gone.pdf)

**Comment by VIRAG-RestAlgo** [comment]
logic change by VMD with UPM.
