### ISSUE TITLE
F7 merge in development branch.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#366]
F7 merge in development branch.

**Comment by Kartik-RestAlgo** [comment]
F7 addtoscript_KAR form merge to anilbhai.

**Comment by Kartik-RestAlgo** [comment]
[NewForm-frmAddToScript.pdf](https://github.com/user-attachments/files/16478182/NewForm-frmAddToScript.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done and updated in live.
