### ISSUE TITLE
Sorting of user master list form

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#368]
Change from virtual grid to normal grid in user master list form and add sorting on columns option on data grid view.

**Comment by Sakshi-Restalgo** [comment]
Status --The development is done, but there is an issue where new data is only staying in memory and the DataGridView is not refreshing; that part is pending

**Comment by Sakshi-Restalgo** [comment]
The development is done, but I have done it in virtual mode because it was the easy way.

**Comment by Sakshi-Restalgo** [comment]
Below is my T368 checkpoint please check and review that
[UserMaterListInSortOrder368.pdf](https://github.com/user-attachments/files/16559787/UserMaterListInSortOrder368.pdf)
