### ISSUE TITLE
Display login indicator on User Master List form

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#369]
Display Green LED indicator for user who are connected and Red LED indicator for user who are not connected in user master list form.

Pass Login context dictionary to admin module to get logged in users. Handle this dictionary in Admin module to indicate online/offline users.

**Comment by Aman-Restalgo** [comment]
hold we need prateek sir for proto

**Comment by Aman-Restalgo** [comment]
I forgot to track my progress on this task. I have been working on it since morning until now.
this task is done in my side

**Comment by Aman-Restalgo** [comment]
[T369_CheckPoint_AdminModule_06-08-2024.pdf](https://github.com/user-attachments/files/16510731/T369_CheckPoint_AdminModule_06-08-2024.pdf)
