### ISSUE TITLE
RTD Excel for Trading Application

### ISSUE THREAD

**Issue by dhruvin-restalgo** [RestAlgo/TradingApplication#37]
This excel is used by Traders for viewing different Spreads together based on different factors such as Expiry dates, IV, Market movement, etc.

Domain Knowledge : Vaibhav Shah

@Deep-RYDT 
Please co-ordinate with the kaushik

**Comment by Kaushik-RYDT** [comment]
1. Today, demo with Lokesh Sir.
2. Discussed adding token Subscribe logic.
3. Need to get the following fields from the "Stock Service" and also add columns for them in the Excel file:
	- AverageTradedPrice
	- HighPrice
	- LowPrice
	- OpenPrice
	- ClosePrice

**Comment by Kaushik-RYDT** [comment]
Point - 3 Development is completed

**Comment by Kaushik-RYDT** [comment]
The logic for adding the subscription token has been completed.

**Comment by dhruvin-restalgo** [comment]
Update?

**Comment by Kaushik-RYDT** [comment]
The development has been completed and handed over to Lokesh Sir.
