### ISSUE TITLE
NSECM Login with real screen

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#372]
NSECM Login with real screen

**Comment by drashti-rydt** [comment]
@VIRAG-RestAlgo   NSECM module coding change using NSEFO module 

learn about config manager with @VIRAG-RestAlgo

**Comment by drashti-rydt** [comment]
development  and testing and merging  done

**Comment by VIRAG-RestAlgo** [comment]
@drashti-rydt update pdf file.

**Comment by VIRAG-RestAlgo** [comment]
Done
