### ISSUE TITLE
Remove "Square Up All" option from Net Position

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#373]
Remove "Square Up All" option from Net Position from Admin Module.

**Comment by Kartik-RestAlgo** [comment]
"Square Up All" option from Net Position Removed
and for square up with market check list count is greater than 0

**Comment by Kartik-RestAlgo** [comment]
This Task Is merge in Task- 370

**Comment by Kartik-RestAlgo** [comment]
[Remove Square Up All option from Net Position_T373.pdf](https://github.com/user-attachments/files/16494139/Remove.Square.Up.All.option.from.Net.Position_T373.pdf)
