### ISSUE TITLE
Display Logged in Admin's own limit utilized in limit tool bar

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#374]
Display Logged in Admin's own limit utilized in limit tool bar as displayed below.

CHECK:
1. When logout from application from "Logout" menu and then login again, limit tool bar repeats. Solve this bug in Admin.
2. Tool Bar should be movable. It is not movable right now.

![Image](https://github.com/user-attachments/assets/121ea428-c4b2-4f27-b584-a9e4c6c7995b)

**Comment by Kartik-RestAlgo** [comment]
[Display Logged in Admin's own limit utilized in limit tool bar_T374.pdf](https://github.com/user-attachments/files/17111250/Display.Logged.in.Admin.s.own.limit.utilized.in.limit.tool.bar_T374.pdf)
