### ISSUE TITLE
Blippers or Event view design

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#375]
Blippers or Event view design

[EventView.docx](https://github.com/user-attachments/files/16495896/EventView.docx)

**Comment by Sakshi-Restalgo** [comment]
Design is done

**Comment by Sakshi-Restalgo** [comment]
Status -- 
i) In frmBlipperCreator I loaded symbols into a ComboBox at the index. -done
ii) Create a new JSON file with one row of data. -- done

**Comment by Sakshi-Restalgo** [comment]
Development Done

**Comment by Sakshi-Restalgo** [comment]
IntraDay Signals -- is design done

**Comment by Sakshi-Restalgo** [comment]
Below is my T375 checkpoint please check and review that
[BlipperEventView375.pdf](https://github.com/user-attachments/files/16560178/BlipperEventView375.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done.
