### ISSUE TITLE
Algo Rule Auto Active Deactive on grid chagne.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#377]
Algo Rule Auto Active Deactive on grid chagne.

**Comment by VIRAG-RestAlgo** [comment]
with new enum

**Comment by Usha-Restalgo** [comment]
change in enum is reminaing so putting this task to hold becuase switching to another task

**Comment by Usha-Restalgo** [comment]
devlopment done and tested by vmd

**Comment by Usha-Restalgo** [comment]
below is my checkpoint for this task

[377-Algo Rule Auto Active Deactive on grid chagne..pdf](https://github.com/user-attachments/files/16522723/377-Algo.Rule.Auto.Active.Deactive.on.grid.chagne.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done

**Comment by VIRAG-RestAlgo** [comment]
Testing Done In Live on date 08-08-2024 by VMD
