### ISSUE TITLE
SL Order request modification and delete

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#383]
SL Order request modification and delete

**Comment by drashti-rydt** [comment]
PENDING WITH @VIRAG-RestAlgo

**Comment by drashti-rydt** [comment]
- sl new order done and create new order book 
- sl old order modification done and update order book

**Comment by VIRAG-RestAlgo** [comment]
This task is merged in develop branch

**Comment by drashti-rydt** [comment]
development done
