### ISSUE TITLE
Total of rule wise net position row required in last row.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#385]
Total of rule wise net position row required in last row.
This point given by client on date 07-08-2024 and communicated by dipakbhai.

**Comment by Anil-Restalgo** [comment]
[T385 Total of rule wise net position row required in last row..pdf](https://github.com/user-attachments/files/16522748/T385.Total.of.rule.wise.net.position.row.required.in.last.row.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Testing done in live on date 08-08-2024 and working ok.
As said APN, as per net position row logic apply in rule wise net position.
