### ISSUE TITLE
Algo Market watch new design for Delhi client

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#404]
-	Algo Watch (Enter to submit as per current logic, on tab, take textbox change value only), No any extra option required on selected row or by right click
1)	Grid Headers (Column seq as per below)
a)	Start/Stop Button
b)	Strategy Name
c)	Fn Lot (s. blue) = FNetLot
d)	FOC lot (gray) = FOLot
e)	FEx Lot (dark navy. blue) = FExLot
f)	Fwd Spd = FPrice
g)	MFs = FS
h)	MRs = RS
i)	Rev Spd = RPrice
j)	Rn Lot = RNetLot
k)	ROC Lot = ROLot
l)	REx Lot = RExLot
m)	Net Lot = FExLot - RExLot
n)	BRK = blank column add now (logic will given by sir very soon)
2)	Disparity Button or Shortcut = Shortcut D
3)	Gset Button or Shortcut = Clt + G
4)	Iset Button or Shortcut = Clt + I

![Image](https://github.com/user-attachments/assets/fac0d574-7f22-4e79-8a1c-8bb5b585f91d)

![Image](https://github.com/user-attachments/assets/1fb9dd11-a446-498c-a4bb-5172b8efc0b6)

**Comment by VIRAG-RestAlgo** [comment]
Copy existing Form and given new name as frmAlgoMarketWatch_NXBlock

**Comment by VIRAG-RestAlgo** [comment]
@Sakshi-Restalgo create demo for button add in virtual grid and tool tip when we over mouse.

**Comment by Sakshi-Restalgo** [comment]
I created a demo in which I added buttons and dummy data, and on mouse over, a tooltip is displayed.

**Comment by Usha-Restalgo** [comment]
as per discussion design is done and tool tip is displayed on mouse hover but have to ask virag sir about lot size in tool tip

**Comment by Usha-Restalgo** [comment]
as per discuss with virag sir and pratik sir lot size have to take from scripmaster so putting this task to return in progress

**Comment by Usha-Restalgo** [comment]
change the color of column header using argb done 
display lotsize in tool tip done
so putting this task to devlopment done

**Comment by Usha-Restalgo** [comment]
added new labels to show ltp ,and indicator in title as per discuss with pratik bhai 
and refresh the label as price change -done
Testing by PPB is remaining

**Comment by Usha-Restalgo** [comment]
as per discuss with dhruvin sir do some changes as per below
-tool tip only on strategy name when strategy name has value
-inline editing and rule activing and deactivating on enter and cell click
-hide labels to show ltp ,and indicator in title

**Comment by Usha-Restalgo** [comment]
below is my checkpoint pdf for this task


[404-Algo Market watch new design for Delhi client.pdf](https://github.com/user-attachments/files/16736589/404-Algo.Market.watch.new.design.for.Delhi.client.pdf)

**Comment by pratik-restalgo** [comment]
Done.
