### ISSUE TITLE
Error Log  data get from json in all exe

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#406]
Error Log  data get from json in all exe and resolve as soon as earlier. 

Amanabhai your responsibility to resolve error log in all exe.

**Comment by Aman-Restalgo** [comment]
Log Update: August 14, 2024

AdminModule: The log for the AdminModule has been updated.
TradingSystem: The log for the TradingSystem has been updated.
Spinner: The log for the Spinner has been updated.
Engine: The log for the Engine has been updated.

**Comment by Aman-Restalgo** [comment]
Log Update: August 29, 2024

AdminModule: The log for the AdminModule has been updated.
TradingSystem: The log for the TradingSystem has been updated.
Spinner: The log for the Spinner has been updated.
Engine: The log for the Engine has been updated.

**Comment by Aman-Restalgo** [comment]
Log Update: August 30, 2024

AdminModule: The log for the AdminModule has been updated.
TradingSystem: The log for the TradingSystem has been updated.
Spinner: The log for the Spinner has been updated.
Engine: The log for the Engine has been updated.

**Comment by Aman-Restalgo** [comment]
this task is handover to support team.
