### ISSUE TITLE
Create new Brokerage Master form

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#409]
Create new brokerage master form as described below:

1. User ID (Text Box): Unique user id list to be displayed using API.
2. Template (Text Box): Unique Template name list from brokerage template master to be displayed using API. If new template name is entered then ask to save. If "Yes" then save in brokerage template master. If "No" then do not save in brokerage master or brokerage template master.
3. Brokerage Details (Data Grid View): 
     a. Exchange: Display help list (NSEFO,NSECM)
     b. Per Amount: Display help list (Per CR)
     c. Normal Intra/Normal Deliver/Option Intra/Option carry forward: All four columns numeric. Allow two decimal values.
4. Update Template (Button): Update only in template master for selected template in "Template" textbox using API.
5. Update User (Button): Update in brokerage master table for selected user using API.

DB Tables:
1. BrokerageMaster
   a. UserID (String)
   b. Template (String)
   c. BrokerageDetails (String). Save brokerage details grid data in json format in string in this field.
3. BrokerageTemplateMaster
   a. Template (String)
   b. BrokerageDetails (String). Save brokerage details grid data in json format in string in this field.

Create APIs to get data from and save/update/delete data to the database tables. (BrokerageMaster/BrokerageTemplateMaster)

[brokage temp.xlsx](https://github.com/user-attachments/files/16632863/brokage.temp.xlsx)

**Comment by Kartik-RestAlgo** [comment]
[Create new Brokerage Master form_T409.pdf](https://github.com/user-attachments/files/17111465/Create.new.Brokerage.Master.form_T409.pdf)

**Comment by pratik-restalgo** [comment]
Done
