### ISSUE TITLE
Error in json for createwatch and algo watch and add rule

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#410]
Error in json for createwatch and algo watch and add rule

**Comment by Anil-Restalgo** [comment]
[CW,AW,AR.json](https://github.com/user-attachments/files/16633061/CW.AW.AR.json)

**Comment by Usha-Restalgo** [comment]
as per discuss with virag bhai  error in frmcreate watch for adding token using F7 is becuase of change in format so not changing code moving to next error

**Comment by Usha-Restalgo** [comment]
frmalgomarketWatch metioned error are solved 
 br_algomarketwatch error are not solved because don't find the reason of error caused
and algorule error is also not solved because cant find the reason of error caused

**Comment by Usha-Restalgo** [comment]
so putting this task to hold

**Comment by Usha-Restalgo** [comment]
putting this task in inProgress  becuse algorule error is also not solved because cant find the reason of error find and solved
want help in Br_algomarketWAtch error
so again putting this task into hold

**Comment by VIRAG-RestAlgo** [comment]
Done. all error solved. and done.
