### ISSUE TITLE
Error in json for netposition and rulewise netposition and appglobal

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#411]
Error in json for netposition and rulewise netposition and appglobal

**Comment by Anil-Restalgo** [comment]
[NP,RNP,APG.json](https://github.com/user-attachments/files/16633064/NP.RNP.APG.json)

**Comment by VIRAG-RestAlgo** [comment]
in this task APN and VMD have resolved attached error in trading application on date 22-08-2024 and deploy same day 10:00 pm.

remaining error is in process by UPM (TaskID 410) and APN (TaskID 411)

[Trading Application Error Log.txt](https://github.com/user-attachments/files/16723645/Trading.Application.Error.Log.txt)

**Comment by VIRAG-RestAlgo** [comment]
[penging errorl.json](https://github.com/user-attachments/files/16939611/penging.errorl.json)

attached json file will handle in new task. and Task ID is 465 and 466,

This task close by VMD.
