### ISSUE TITLE
In Manual Order Modification Strategy filed blank send

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#419]
In Live Date 20-08-2024
In Manual Order Modification Strategy filed blank send

[TradingApplication20240820.zip](https://github.com/user-attachments/files/16685942/TradingApplication20240820.zip)

AppOrder ID 102 and 1089

**Comment by Usha-Restalgo** [comment]
Log check done and discussed with virag sir
so putting this task to devlopment done

**Comment by VIRAG-RestAlgo** [comment]
Ok Checked logic and need to set one validation and that task will create in new task.
