### ISSUE TITLE
In NetPosition error for entry datetime format

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#426]
In NetPosition error for entry datetime format.

Anilbhai will explain you with demo.

**Comment by Sakshi-Restalgo** [comment]
discussion pending with virag sir and lokesh sir.

**Comment by Sakshi-Restalgo** [comment]
Logic change of date store in Application With discuss ViragSir and LokeshSir.

**Comment by VIRAG-RestAlgo** [comment]
This task new created by VMD and TaskID 466 so this task move to Done.
