### ISSUE TITLE
FileDownload (Transplexer)

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#43]
Code re structure as per attached document.

[Downloader.txt](https://github.com/RestAlgo/TradingApplication/files/15235156/Downloader.txt)

**Comment by Anil-Restalgo** [comment]
[T43 FileDownload(Transplexer).pdf](https://github.com/user-attachments/files/15585703/T43.FileDownload.Transplexer.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done

**Comment by VIRAG-RestAlgo** [comment]
Complete Date On 03-07-2024 due to in between some other priority work allot to @Anil-Restalgo
