### ISSUE TITLE
In Market Depth, if we change Option Type then Strike Price automatically changed.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#432]
In Market Depth, if we change Option Type then Strike Price automatically changed.

Ref. https://github.com/RestAlgo/Bugs/issues/65

**Comment by Kartik-RestAlgo** [comment]
Done And Merger to VMD

**Comment by VIRAG-RestAlgo** [comment]
Done and working ok in live.
