### ISSUE TITLE
In Algo rule window every leg details should same as first leg.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#433]
In Algo rule window every leg details should same as first leg.

Ref. https://github.com/RestAlgo/Bugs/issues/69

**Comment by Kartik-RestAlgo** [comment]
Done.
Change in UpdatTextBoxValue Method

**Comment by VIRAG-RestAlgo** [comment]
@Kartik-RestAlgo and @Usha-Restalgo this task move to TODO due to need to implement in new algo rule form

**Comment by VIRAG-RestAlgo** [comment]
Done

**Comment by Usha-Restalgo** [comment]
this method is already added in new algorule form and check point is avialbe in task no 482
