### ISSUE TITLE
Add Indices tool bar in trading system

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#435]
Add new tool bar in trading system for Indices view.
1. Display LTP and difference % for added tokens in single label in tool bar with | separator.
2. Update LTP for every tick.

New Requirement on date 06-09-2024 (Given by Dhruvinbhai and discussed with Lokesh Sir) as below:
* On double click on tool bar, open new form to modify tokens added in tool bar.
* Add 5 textboxes.
* Fill indices list as autocomplete list in all 5 text boxes.
* Read the token text file and token name in the text boxes
* When change value in any textbox, update token text file and reload all data and refresh tool bar.

**Comment by VIRAG-RestAlgo** [comment]
This is in NX Block

**Comment by Usha-Restalgo** [comment]
forget to take it in in progress  task start at 14.35

**Comment by Usha-Restalgo** [comment]
development done of this task so putting this task to development done

**Comment by Usha-Restalgo** [comment]
my check point pdf for this task is below


[435-Add new tool bar in trading system for Indices view..pdf](https://github.com/user-attachments/files/16736496/435-Add.new.tool.bar.in.trading.system.for.Indices.view.pdf)

**Comment by Usha-Restalgo** [comment]
testing by PPB is remaining

**Comment by VIRAG-RestAlgo** [comment]
Conceptually logic changes need.
@Kartik-RestAlgo please make changes as discussed today

**Comment by Usha-Restalgo** [comment]
changes is done as per discussion so putting this task to development done

**Comment by pratik-restalgo** [comment]
New Requirement on date 06-09-2024 (Given by Dhruvinbhai and discussed with Lokesh Sir) as below:
* On double click on tool bar, open new form to modify tokens added in tool bar.
* Add 5 textboxes.
* Fill indices list as autocomplete list in all 5 text boxes.
* Read the token text file and token name in the text boxes
* When change value in any textbox, update token text file and reload all data and refresh tool bar.

**Comment by Usha-Restalgo** [comment]
as per new requirement task is done so putting this task to devlopment done 
and adding below check point as per new requirmnet

[435 V2.pdf](https://github.com/user-attachments/files/16926268/435.V2.pdf)
