### ISSUE TITLE
NSECM security.txt (contract file load and read broadcast)

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#442]
NSECM security.txt (contract file load and read broadcast)

**Comment by VIRAG-RestAlgo** [comment]
This task is complete and tested in yesterday live market.

NSECM Contract load - Done
NSECM New token add in normal marketwatch - Done
BroadCast read for that token - Done (But NSECM packet change form broadcast show proper packet not read)

This task complete by VMD and DJK. 

As per this ref. DJK was work in NSECM Delegate NSECM contract load.

**Comment by drashti-rydt** [comment]
![Image](https://github.com/user-attachments/assets/57b3817b-7df9-4f2c-ba58-a870ccc28f6c)

**Comment by VIRAG-RestAlgo** [comment]
Ok Done.
