### ISSUE TITLE
Token Selector issue while change Strikeprice

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#446]
Token Selector issue while change Strikeprice

**Comment by Kartik-RestAlgo** [comment]
Resolved
=====
value of strikeprice or OptionType or ExpiryDate will remain same after Changing it by tab or Up/Down key

**Comment by VIRAG-RestAlgo** [comment]
Done merge in live master and develop branch.

**Comment by Jill-Restalgo** [comment]
exact tame kya aa point na changes karya che plz amne samjavo.
