### ISSUE TITLE
ErroLog 29-08-2024

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#447]
ErroLog 29-08-2024

[ClientLog_29-08-2024.json](https://github.com/user-attachments/files/16812639/ClientLog_29-08-2024.json)

**Comment by drashti-rydt** [comment]
solve all error with reason   Date 30-08-2024

[ClientLog_29-08-2024.json](https://github.com/user-attachments/files/16815982/ClientLog_29-08-2024.json)

Merging  Pending    @VIRAG-RestAlgo   Side Testing Pending 

Checkpoint File Uploaded please check it 

[CheckPoint_T447.xlsx](https://github.com/user-attachments/files/16816281/CheckPoint_T447.xlsx)

**Comment by VIRAG-RestAlgo** [comment]
**Below error given to VMD in TaskID 466**
{
			"Timestamp": "2024-08-29T10:25:35.8357643+05:30",
			"Level": "Error",
			"MessageTemplate": "{Error}",
			"Properties": {
				"Information": null,
				"Error": {
					"FormName": "BR_NetPosition - BpRM6cUwi9WX1xcNGWNb",
					"Message": "System.FormatException: String was not recognized as a valid DateTime.\r\n   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)\r\n   at System.Convert.ToDateTime(String value)\r\n   at XVllgBHNmEwGDlfMkA1S.a3UHK03m5qm(String , XVllgBHNmEwGDlfMkA1S )\r\n   at TradingSystem.BusinessRule.NetPosition.BR_NetPosition.UpdateNetPositionRow(TradeBookRow _TradeBookRow) in D:\\Live\\VMD\\TradingSystem\\TradingSystem\\BusinessRule\\NetPosition\\BR_NetPosition.cs:line 68"
				}
			}
		},
		{
			"Timestamp": "2024-08-29T10:25:35.8497595+05:30",
			"Level": "Error",
			"MessageTemplate": "{Error}",
			"Properties": {
				"Information": null,
				"Error": {
					"FormName": "AppGlobal.UpdateRuleWiseNetPositionRow",
					"Message": "System.FormatException: String was not recognized as a valid DateTime.\r\n   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)\r\n   at System.Convert.ToDateTime(String value)\r\n   at XVllgBHNmEwGDlfMkA1S.a3UHK03m5qm(String , XVllgBHNmEwGDlfMkA1S )\r\n   at TradingSystem.AppGlobal.kQEHoD71Dr(Object  ) in D:\\Live\\VMD\\TradingSystem\\TradingSystem\\AppGlobal.cs:line 972"
				}
			}
		}

**Comment by VIRAG-RestAlgo** [comment]
rest is Ok. and merge in master branch.
