### ISSUE TITLE
Change broadcast IP/Port dynamically and give effect while exe running

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#448]
Change broadcast IP/Port when application running and and read from new IP/Port.

**Comment by Kartik-RestAlgo** [comment]
try to change dynamically broadcast IP/Port 
if we change IP/Port than broadcast will stop but when 
we correct IP/Port than broadcast is not starting again

**Comment by VIRAG-RestAlgo** [comment]
This task is covert in #514 by VMD.
