### ISSUE TITLE
Spinner and Gateway connect and disconnect date time in message log in trading application.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#45]
Spinner and Gateway connect and disconnect date time in message log in trading application.

**Comment by VIRAG-RestAlgo** [comment]
Done by @Sakshi-Restalgo 
and merge by @VIRAG-RestAlgo

**Comment by VIRAG-RestAlgo** [comment]
@Sakshi-Restalgo    send me Check point.

**Comment by Sakshi-Restalgo** [comment]
Check point

[CheckPoin-MessageOnDateTime.pdf](https://github.com/user-attachments/files/15603251/CheckPoin-MessageOnDateTime.pdf)
