### ISSUE TITLE
Order Preferences

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#451]
+/- Buy Qty : When press up/down key on Qty text box, +/- Qty in lots specified in this field. Rename caption to "+/- by Qty".
+/- by Ticks: When press up/down key on Price text box, +/- Price in ticks as per script master, specified in this field.

Hide Refresh combo box.

**Comment by Usha-Restalgo** [comment]
this task development is done so putting this task to development done

**Comment by Usha-Restalgo** [comment]
below is my check point for this task

[451-orderPrefrence.pdf](https://github.com/user-attachments/files/16926099/451-orderPrefrence.pdf)

**Comment by VIRAG-RestAlgo** [comment]
This task create by Pratikbhai and work by Usha ben today both are not available so this task move to done by me, and today Order Preference working Ok as per need by client and support.
