### ISSUE TITLE
SID -> Changes as per demo on date 03-09-2024

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#454]
1. Try catch
2. Property
3. Start, Stop and Clean.
4. NSECM Token add issue - Enter on Exchange token can't enter.
5. If font size increase then row height should be update as per font (if required then discussed with Lokeshsir)

**Comment by Anil-Restalgo** [comment]
1 . Try catch **(Done)**
2. Property **(Done)**
3. Start, Stop and Clean. **(Pending)**
4. NSECM Token add issue - Enter on Exchange token can't enter. **(Pending)**
5. If font size increase then row height should be update as per font (if required then discussed with Lokeshsir) **(Pending)**

**Comment by VIRAG-RestAlgo** [comment]
Point No 1,2 merge in develop branch and master branch. and deploy in live and send new exe to support.

**Comment by Anil-Restalgo** [comment]
3. Start, Stop and Clean. (**Done**)(**Testing Pending**)
4. NSECM Token add issue - Enter on Exchange token can't enter. (**Done**)

**Comment by VIRAG-RestAlgo** [comment]
New Point added as discussed with Dhruvinbhai and Lokeshsir.

Point : Exchange NSEFO  FUTSTK current month data show in intraday signal

**Comment by Anil-Restalgo** [comment]
All Above Points Will Be Done.

and With This Also Done Of  :-
1. **On Run Program Add Edit Update.**
2. **On Run Script Wise Template Activate Done.**
3. **Proper Testing Done.**
4. **Only msg edit then Complete Work.**
5. **Dependency not included in This of CreateWatch Form.**
6. **On Run Change BlipView , MsgBar and DialogBox Complete.**
7. **On Run Rule Active Deactive Complete.**
8. **Single Event and Multiple Time Show Msg Done.**
