### ISSUE TITLE
Ratio change issue

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#456]
Ratio change issue.

1st time we set ratio  1 - 2 - 1 and then increased 2-4-2 and then we set 1-2- is not working property and ordering not sent properly.

**Comment by drashti-rydt** [comment]
04-09-2024
=================================
in progress  As Per Discuss With @VIRAG-RestAlgo

**Comment by drashti-rydt** [comment]
05-09-2024
======================
in progress As Per Discuss With @VIRAG-RestAlgo

**Comment by VIRAG-RestAlgo** [comment]
Done and 1st testing done by Dipakbhai in BVN server. deployment send.
