### ISSUE TITLE
SID -> Implement NSEFO in CM Indicator module.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#457]
SID -> Implement NSEFO in CM Indicator module.

**Comment by VIRAG-RestAlgo** [comment]
NSEFO contract loaded with NSECM. and token added normal marketwatch and depth.

**Comment by Anil-Restalgo** [comment]
BroadCast Get of NSEFO and NSECM.

**Comment by Anil-Restalgo** [comment]
1. **On Run Program Add Edit Update.**
2. **On Run Script Wise Template Activate Done.**
3. **Proper Testing Done.**
4. **Only msg edit then Complete Work.**
5. **Dependency not included in This of CreateWatch Form.**
6. **On Run Change BlipView , MsgBar and DialogBox Complete.**
7. **On Run Rule Active Deactive Complete.**
8. **Single Event and Multiple Time Show Msg Done.**
