### ISSUE TITLE
NXBlock -> AlgoRule

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#458]
1. Add new form as AlgoRule
2. Des. same as old.
3. Template facility remove.
4. Strategy Add : Butterfly, PriceDiff, ConvRev

* Butterfly : NoOfLeg : 3 (lock)
* ConvRev : NoOfLeg : 3 (lock)
* PriceDiff : NoOfLeg : 4 (not lock)

Make logic as discussed.

**Comment by Usha-Restalgo** [comment]
need help in modify frm algo rule so putting this task to hold

**Comment by Usha-Restalgo** [comment]
trying to solve error so putting this task to in progress again

**Comment by Usha-Restalgo** [comment]
issue is solved so putting this task to development done

**Comment by VIRAG-RestAlgo** [comment]
@Aman-Restalgo  and @Usha-Restalgo this task move to TODO due to need to change logic as per pronto strategy wise diff. diff. algo leg control

**Comment by Usha-Restalgo** [comment]
as per pronto strategy wise diff. diff. algo leg control code is merged to branch VMD_DEVLOP_TAsk482
-07102024 with Drshati madam
so putting this task to development done

**Comment by Usha-Restalgo** [comment]
[458-Nxblock ALgoRule.pdf](https://github.com/user-attachments/files/17528992/458-Nxblock.ALgoRule.pdf)

**Comment by VIRAG-RestAlgo** [comment]
New concept of algo rule is updated in NXBlock application.
