### ISSUE TITLE
Order Modification

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#46]
Order modification open by only shift + F2 only.

If multiple row selected then and same row token same then open order modification price form.

If single row select and press shift + f2 then open as per existing.

**Comment by Aman-Restalgo** [comment]
I am attached  Check Point.

[T_46_CheckPoint_TradingSystem_07-05-2024.pdf](https://github.com/RestAlgo/TradingApplication/files/15384417/T_46_CheckPoint_TradingSystem_07-05-2024.pdf)

**Comment by Aman-Restalgo** [comment]
I am working on this task some changes code Done

**Comment by VIRAG-RestAlgo** [comment]
Done and working in live trading exe.
