### ISSUE TITLE
As per New API 9.40

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#462]
Two new error code added in API 9.40

[TP_FO_Trimmed_NNF_PROTOCOL_9.40.pdf](https://github.com/user-attachments/files/16903447/TP_FO_Trimmed_NNF_PROTOCOL_9.40.pdf)

**Comment by brunoR1000** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by drashti-rydt** [comment]
06-09-2024
====================================
Development Done  Code Committed in git Branch  only Merging Pending

**Comment by VIRAG-RestAlgo** [comment]
This is merged in master branch.
