### ISSUE TITLE
Net Amount in Net Position

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#464]
Add new field of Net Amount in Net Position.
Discuss with VMD

**Comment by VIRAG-RestAlgo** [comment]
@Sakshi-Restalgo  please submit pdf. 

merge in live and testing ok in live today.

**Comment by Sakshi-Restalgo** [comment]
below is my checkpoint pdf for this task[CheckPoint-TaskId - 464.pdf](https://github.com/user-attachments/files/16993289/CheckPoint-TaskId.-.464.pdf)
