### ISSUE TITLE
GridColor error

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#465]
{
			"Timestamp": "2024-08-14T15:01:55.5109960+05:30",
			"Level": "Error",
			"MessageTemplate": "{Error}",
			"Properties": {
				"Information": null,
				"Error": {
					"FormName": "AppGlobal - kdQm17hVZFTl77gbowDV",
					"Message": "System.ArgumentException: Color 'GridColor' cannot be set to a transparent color.\r\n   at System.Windows.Forms.DataGridView.set_GridColor(Color value)\r\n   at qveqsZhTL1dZOLnkx42k.zDphcSfUeuQ(Object , Color , qveqsZhTL1dZOLnkx42k )\r\n   at TradingSystem.AppGlobal.ApplyNewProperties(Control ___FormObj, String ___FormName) in D:\\Live\\VMD\\TradingSystem\\TradingSystem\\AppGlobal.cs:line 1447"
				}
			}
		}

**Comment by Anil-Restalgo** [comment]
[T465 GridColor Error..pdf](https://github.com/user-attachments/files/17328060/T465.GridColor.Error.pdf)
