### ISSUE TITLE
NXBlock -> Change menu bar Sequence

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#468]
**Menu bar Sequence**

Login/Logout
Market Watch
Market depth
Algo Market Watch
Net Position
Combine Tracker
Trade Tracker/ Trade book
Rule Wise Net Position
Pending Order Book
Message Bar
Csv Export
Workspace Save
Setting
About

**Comment by Aman-Restalgo** [comment]
this task is done

**Comment by Aman-Restalgo** [comment]
[T468_CheckPoint_AdminModule_10-09-2024.pdf](https://github.com/user-attachments/files/16962431/T468_CheckPoint_AdminModule_10-09-2024.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done
