### ISSUE TITLE
Pronto -> NSECM Contract file load and token add to market watch with broadcast.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#469]
Pronto -> NSECM Contract file load and token add to market watch with broadcast as per SID branch.

**Comment by drashti-rydt** [comment]
**10-09-2024**
--------------------------------------------------------------------------------------------------------------------------------------------------

**Task No -- 469** -- Pronto-> NSECM Contract file load and token add to market watch with broadcast.
**Status** ---Work in Progress

**Comment by drashti-rydt** [comment]
11-09-2024
===============================================
Status - Development  Done

**Comment by VIRAG-RestAlgo** [comment]
Done and updated in live  and testing Ok in live today.
