### ISSUE TITLE
NXBlock -> Change in Indices Toolbar

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#471]
in indices tool bar separate symbol and LTP labels.
Add total 5 labels for Symbols and 5 labels for LTP.

**Comment by Usha-Restalgo** [comment]
development done so putting this task to development done

**Comment by VIRAG-RestAlgo** [comment]
Logic corrected by me today and deploy in live.

**Comment by Usha-Restalgo** [comment]
[471-NXBlock -Change in Indices Toolbar.pdf](https://github.com/user-attachments/files/16962374/471-NXBlock.-Change.in.Indices.Toolbar.pdf)
