### ISSUE TITLE
NXBlock -> Error in json

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#472]
@Sakshi-Restalgo please solve attached json file which is solved in Pronto. @drashti-rydt will help you in some errors.[SKP.json](https://github.com/user-attachments/files/16957724/SKP.json)

**Comment by drashti-rydt** [comment]
11-09-2024
===================================
Development Done

**Comment by VIRAG-RestAlgo** [comment]
Done and merge in live branch,.
