### ISSUE TITLE
Pronto -> Box Strategy Rule Create and Add MarketWatch

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#476]
Box Strategy Rule Create and Add MarketWatch

**Comment by Usha-Restalgo** [comment]
task is done so moving this task to development done

**Comment by Usha-Restalgo** [comment]
facing error in modifcation of algorrule box stratagy so putting this task to hold

**Comment by pratik-restalgo** [comment]
Please add Checkpoint.

**Comment by Usha-Restalgo** [comment]
below is my chekpoint for this point:
[476-BoxStratagy.pdf](https://github.com/user-attachments/files/17108646/476-BoxStratagy.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done.
