### ISSUE TITLE
NXBlock -> NSECM Order Process and Order Slicing From Trading System

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#477]
NXBlock -> NSECM Order Process and Order Slicing From Trading System

**Comment by Sakshi-Restalgo** [comment]
Development done for  NXBlock -> NSECM Order Process and Order Slicing From Trading System .
testing done by for my side. and pending with virag sir.

**Comment by Sakshi-Restalgo** [comment]
-- I completed the task in 30 minutes.
-- Task 477 has checkpoints; please check and review them.
[CheckPoint--TaskId-477FO-CM.pdf](https://github.com/user-attachments/files/16992828/CheckPoint--TaskId-477FO-CM.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done.

**Comment by VIRAG-RestAlgo** [comment]
When required NXBlock system at that time we will copy from pronto to NXBlock.
