### ISSUE TITLE
Pronto -> Algo Rule Form Segregate as per strategy

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#482]
Algo Rule Form Segregate as per strategy.

Step by Step VMD logic given

**Comment by Usha-Restalgo** [comment]
As per discuss with Lokesh sir **PriceDiff,ConRev,Box,Buttefly** strategy  controls are created and accroding to strategy legs are created and rule is added  to algoMarketWatch Form on AddRule button
Load Template on form load is done
Create New Template is remain
Validation is remain when add rule

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo and @Aman-Restalgo  Add Straddle strategy in this task.

**Comment by VIRAG-RestAlgo** [comment]
pdf submit karjo

**Comment by VIRAG-RestAlgo** [comment]
As per new concept update logic in template save.
@Usha-Restalgo and @Aman-Restalgo

**Comment by Usha-Restalgo** [comment]
create and save tamplate work is done so putting this task to development done

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo please submit pdf.

**Comment by Usha-Restalgo** [comment]
[482-segregated algorule manager.pdf](https://github.com/user-attachments/files/17253448/482-segregated.algorule.manager.pdf)
