### ISSUE TITLE
Pronto -> Error Log Dated 17-09-2024

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#483]
Pronto -> Error Log Dated 17-09-2024

**Comment by VIRAG-RestAlgo** [comment]
[tradingLog_17-09-2024.json](https://github.com/user-attachments/files/17038680/tradingLog_17-09-2024.json)

**Comment by Sakshi-Restalgo** [comment]
Trading system in found error from log file and 3 error is not found in trading system. I need help with @virag sir for finding the 3 error.

**Comment by Sakshi-Restalgo** [comment]
finding error is done and resolving done error with virag sir

**Comment by Sakshi-Restalgo** [comment]
Development done

**Comment by VIRAG-RestAlgo** [comment]
Done...

[Solved_ErrorLogFile.json](https://github.com/user-attachments/files/17306853/Solved_ErrorLogFile.json)
