### ISSUE TITLE
Pronto -> Meeting On Date 17-09-2024 changes or correction in AMW

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#484]
Meeting On Date 17-09-2024 changes or correction in AMW update in (Pronto and NXBlock)

	1. Order Lot set in AMW as per Gset. (UPM / VMD)
	
	2. If ISet not set and user open ISet form then show data as per Gset, also Button name Change as per menu open GSet Or ISet (KAR / SKP)
	 
	3. FPrice and RPrice set as 0 or Blank. (UPM / VMD)

**Comment by Kartik-RestAlgo** [comment]
Point no 2 Done.
Virag Bhai Please Check and Merge.

**Comment by Kartik-RestAlgo** [comment]
Design Changes Done in G-Set Form New Buttons added.

**Comment by Kartik-RestAlgo** [comment]
Point No 1 Done
Set Default OrderLot in FOrderLot and ROrderLot in Algo rule

**Comment by VIRAG-RestAlgo** [comment]
Done and FPrice and RPrice blank issue resolved.
@Kartik-RestAlgo please submit checkpoint.

**Comment by Kartik-RestAlgo** [comment]
[OrderLot-GSet ISet-FPrice RPrice_T484.pdf](https://github.com/user-attachments/files/17107646/OrderLot-GSet.ISet-FPrice.RPrice_T484.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done
