### ISSUE TITLE
Add Strategy Name filter in Net Position

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#491]
Add new filter on Strategy Name field in Net Position.

Reference https://github.com/orgs/RestAlgo/projects/6?pane=issue&itemId=80065823

**Comment by pratik-restalgo** [comment]
Add check point. @Kartik-RestAlgo

**Comment by Kartik-RestAlgo** [comment]
[Add Strategy Name filter in Net Position_T491.pdf](https://github.com/user-attachments/files/17111041/Add.Strategy.Name.filter.in.Net.Position_T491.pdf)

**Comment by pratik-restalgo** [comment]
Done
