### ISSUE TITLE
Delete script from Restrict script form and Ban Script

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#50]
When any script is added and then delete, it is not deleted and when we delete script and close the form and reopen, it is shown.

**Comment by Aman-Restalgo** [comment]
[T_50_CheckPoint_TradingSystem_21-05-2024.pdf](https://github.com/RestAlgo/TradingApplication/files/15384929/T_50_CheckPoint_TradingSystem_21-05-2024.pdf)
