### ISSUE TITLE
Strangle rule added in algo market watch.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#503]
Strangle rule added in algo market watch.
[Strangle.xlsx](https://github.com/user-attachments/files/17238876/Strangle.xlsx)

**Comment by Usha-Restalgo** [comment]
this task is already developed yesterday date 04-10-2024 so putting this task to development done

**Comment by Usha-Restalgo** [comment]
below is my check point for this task[503-strangle.pdf](https://github.com/user-attachments/files/17265158/503-strangle.pdf)

**Comment by drashti-rydt** [comment]
NXBlock Branch Code Merging Pending for Develop branch merging Work with @Usha-Restalgo 
VMD_DJK_TaskID503_NXblock_06112024_1048 in this branch this taskid code commited

**Comment by VIRAG-RestAlgo** [comment]
Done
