### ISSUE TITLE
Apply common properties in all forms

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#507]
If properties not found for any form then get default common properties from either class constructor or file.

**Comment by Anil-Restalgo** [comment]
[T507 Apply Comman Properties In All Forms..pdf](https://github.com/user-attachments/files/17306830/T507.Apply.Comman.Properties.In.All.Forms.pdf)

**Comment by pratik-restalgo** [comment]
Done
