### ISSUE TITLE
Pincode must be of 6 digits in User Master form.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#51]
Add validation in user master that pin code must be of 6 digits.
no alphabets, special characters or space should be allowed in pin code field.

**Comment by Aman-Restalgo** [comment]
[T_51_CheckPoint_TradingSystem_21-05-2024.pdf](https://github.com/RestAlgo/TradingApplication/files/15384770/T_51_CheckPoint_TradingSystem_21-05-2024.pdf)
