### ISSUE TITLE
Straddle Strategy allow 0 ratio

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#512]
As discussed with Vaibhavbhai and Dipakbhai, Straddle Strategy allow 0 ratio,.

means show CE and PE single while 0 ratio.

**Comment by VIRAG-RestAlgo** [comment]
In Pronto Done and deployment also done.

**Comment by VIRAG-RestAlgo** [comment]
@drashti-rydt need to develop this task in NXBlock

**Comment by drashti-rydt** [comment]
Development Done

**Comment by VIRAG-RestAlgo** [comment]
Code by VMD in pronto and same code apply in nxblock by UPM and DJK.
