### ISSUE TITLE
BOX_IOC

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#521]
BOX_IOC strategy develop as per BOX only validity will IOC.

This task required in Pronto and NX Both.

**Comment by Usha-Restalgo** [comment]
devlopment done so puuting this task to devlopment done

**Comment by Usha-Restalgo** [comment]
below is my check point pdf for this task:
[521-BoxRule_IOC.pdf](https://github.com/user-attachments/files/17489646/521-BoxRule_IOC.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done.
If required in NXBlock then we will update in features.
