### ISSUE TITLE
Execute Lot - FW / RW

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#522]
FW / RW Execute lot in Pronto and NX both application.

**Comment by VIRAG-RestAlgo** [comment]
In Pronto Done.

**Comment by Usha-Restalgo** [comment]
this branch is merged to NX Block on date 24102024
In Branch Name UPM_T522_NXBLOCK_24102024

**Comment by VIRAG-RestAlgo** [comment]
As on date as required by support and Vaibhavbhai all execute lot show proper in screen.
