### ISSUE TITLE
Straddle, Strangle and Butterfly IOC rule create

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#524]
Straddle, Strangle and Butterfly IOC rule create.

This is required in both application.

**Comment by Usha-Restalgo** [comment]
Development done so putting this task to development done

**Comment by Usha-Restalgo** [comment]
below is my chekpoint for this task :[524-Straddle, Strangle and Butterfly IOC rule create.pdf](https://github.com/user-attachments/files/17489693/524-Straddle.Strangle.and.Butterfly.IOC.rule.create.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done.
