### ISSUE TITLE
Error 11-11-2024 with Dubai client

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#535]
[Error 11-11-2024 with Dubai client.txt](https://github.com/user-attachments/files/17712021/Error.11-11-2024.with.Dubai.client.txt)
Error 11-11-2024 with Dubai client.

**Comment by drashti-rydt** [comment]
Development Done

**Comment by Usha-Restalgo** [comment]
error of Form Load taking time is devlopment done and merged with VMD

**Comment by VIRAG-RestAlgo** [comment]
Bug
1. Strangle 2 - 4 leg isn't open. (ARV) - Done
2. PriceDiff, Straddle, strangle Side is not proper work. (VMD) - Done
3. SquerOff with market all in NP issue. (VMD) - Done
4. Refresh issue in margin. (PPB)
5. Rule form open slow. (UPM) - Done
6. Admin : Refresh issue. (PPB)
7. PriceDiff_IOC noOfLeg 1 and show 3 Leg. (DJK) - Done
8. exe close automatically. (VMD)

**Comment by drashti-rydt** [comment]
14-11-2024
======================================================
 All  Task Development Done  in NXBlock Only merging Pending

**Comment by Aman-Restalgo** [comment]
Strangle 2 - 4 leg isn't open. (ARV) -Development Done and merging done

**Comment by VIRAG-RestAlgo** [comment]
**Some Error in Json file as following. (Solved by @Sakshi-Restalgo  Test By @VIRAG-RestAlgo )**

1. 2024-11-11 11:56:26.933 +05:30 [ERR] GenerateOrderBook - xDTVJymHPjKu0L6x77wv - System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TradingSystem.GenerateOrderBook.GenerateOrderBookRow(ClientOrderRequest _ClientOrderRequest) in D:\Live\VMD\TradingSystem\TradingSystem\AppClasses\GenerateOrderBook.cs:line 39

2.   2024-11-11 11:56:26.980 +05:30 [ERR] BR_NormalOrderRequestManager.StartProcessOrderRequest - Error message System.NullReferenceException: Object reference not set to an instance of an object.
   at gmiHjLtF95ZPJMhoiOO.WIPvj3tR0RkuS2o1tqZ.TcJl2SO8Eqk83iT4WgIy(Object )
   at gmiHjLtF95ZPJMhoiOO.WIPvj3tR0RkuS2o1tqZ.NFvtj7xj7a(Object  , Object  ) in D:\Live\VMD\TradingSystem\TradingSystem\BusinessRule\NormalOrder\BR_NormalOrderRequestManager.cs:line 63

3. 2024-11-11 12:15:50.483 +05:30 [ERR] frmCreateWatch - Tt1x37msjyMkvbZRmOhG - System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewSelectedRowCollection.get_Item(Int32 index)
   at DlBg8JbcwrL5roZ4osg4.eMtbitKdGGW(Object , Int32 , DlBg8JbcwrL5roZ4osg4 )
   at TradingSystem.frmCreateWatch.zStjiNJ8Uo(String  , ScriptMasterRow  ) in D:\Live\VMD\TradingSystem\TradingSystem\Forms\TradingClient\frmCreateWatch.cs:line 1590
   
   
4.    //apply the condition null hoga to retur kiya
2024-11-12 09:48:33.743 +05:30 [ERR] ffrmAlgoMarketWatch - p2BUhQm3Iy4tkHR2MKKK - System.NullReferenceException: Object reference not set to an instance of an object.
   at (Object )
   at qp2u3kbaHY11lLaJSJMb.eMtbitKdGGW(Object , qp2u3kbaHY11lLaJSJMb )
   at TradingSystem.ffrmAlgoMarketWatch.ProcessCmdKey(Message& msg, Keys keyData) in D:\Live\VMD\TradingSystem\TradingSystem\Forms\AlgoClient\ffrmAlgoMarketWatch.cs:line 2306   

5. "Timestamp": "2024-09-18T14:45:22.6043561+05:30"
			"Level": "Error",
			"MessageTemplate": "{Error}",
			"Properties": {
				"Information": null,
				"Error": {
					"FormName": "RYDTEngineResponseAction - MoveNext",
					"Message": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n  
					"at (Object , DialogResult )\r\n   
					"at H7LkaKIGO9XBUbe1w4mT.Kb9IHg3KFhT(Object , DialogResult , H7LkaKIGO9XBUbe1w4mT )\r\n   
					"at TradingSystem.RYDTEngineResponseAction.<LogInResponse>d__8.MoveNext() in ",
					"D:\\Live\\VMD\\TradingSystem\\TradingSystem\\AppClasses\\RYDTEngineResponseAction.cs:line 344"
				}
			}

**Comment by VIRAG-RestAlgo** [comment]
> **Some Error in Json file as following. (Solved by [@Sakshi-Restalgo](https://github.com/Sakshi-Restalgo) Test By [@VIRAG-RestAlgo](https://github.com/VIRAG-RestAlgo) )**
> 
> 1. 2024-11-11 11:56:26.933 +05:30 [ERR] GenerateOrderBook - xDTVJymHPjKu0L6x77wv - System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
>    at System.ThrowHelper.ThrowKeyNotFoundException()
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at TradingSystem.GenerateOrderBook.GenerateOrderBookRow(ClientOrderRequest _ClientOrderRequest) in D:\Live\VMD\TradingSystem\TradingSystem\AppClasses\GenerateOrderBook.cs:line 39
> 2. 2024-11-11 11:56:26.980 +05:30 [ERR] BR_NormalOrderRequestManager.StartProcessOrderRequest - Error message System.NullReferenceException: Object reference not set to an instance of an object.
>    at gmiHjLtF95ZPJMhoiOO.WIPvj3tR0RkuS2o1tqZ.TcJl2SO8Eqk83iT4WgIy(Object )
>    at gmiHjLtF95ZPJMhoiOO.WIPvj3tR0RkuS2o1tqZ.NFvtj7xj7a(Object  , Object  ) in D:\Live\VMD\TradingSystem\TradingSystem\BusinessRule\NormalOrder\BR_NormalOrderRequestManager.cs:line 63
> 3. 2024-11-11 12:15:50.483 +05:30 [ERR] frmCreateWatch - Tt1x37msjyMkvbZRmOhG - System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>    Parameter name: index
>    at System.Collections.ArrayList.get_Item(Int32 index)
>    at System.Windows.Forms.DataGridViewSelectedRowCollection.get_Item(Int32 index)
>    at DlBg8JbcwrL5roZ4osg4.eMtbitKdGGW(Object , Int32 , DlBg8JbcwrL5roZ4osg4 )
>    at TradingSystem.frmCreateWatch.zStjiNJ8Uo(String  , ScriptMasterRow  ) in D:\Live\VMD\TradingSystem\TradingSystem\Forms\TradingClient\frmCreateWatch.cs:line 1590
> 4. //apply the condition null hoga to retur kiya
>    2024-11-12 09:48:33.743 +05:30 [ERR] ffrmAlgoMarketWatch - p2BUhQm3Iy4tkHR2MKKK - System.NullReferenceException: Object reference not set to an instance of an object.
>    at (Object )
>    at qp2u3kbaHY11lLaJSJMb.eMtbitKdGGW(Object , qp2u3kbaHY11lLaJSJMb )
>    at TradingSystem.ffrmAlgoMarketWatch.ProcessCmdKey(Message& msg, Keys keyData) in D:\Live\VMD\TradingSystem\TradingSystem\Forms\AlgoClient\ffrmAlgoMarketWatch.cs:line 2306
> 5. "Timestamp": "2024-09-18T14:45:22.6043561+05:30"
>    "Level": "Error",
>    "MessageTemplate": "{Error}",
>    "Properties": {
>    "Information": null,
>    "Error": {
>    "FormName": "RYDTEngineResponseAction - MoveNext",
>    "Message": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n
>    "at (Object , DialogResult )\r\n
>    "at H7LkaKIGO9XBUbe1w4mT.Kb9IHg3KFhT(Object , DialogResult , H7LkaKIGO9XBUbe1w4mT )\r\n
>    "at TradingSystem.RYDTEngineResponseAction.d__8.MoveNext() in ",
>    "D:\Live\VMD\TradingSystem\TradingSystem\AppClasses\RYDTEngineResponseAction.cs:line 344"
>    }
>    }

This is merged in master and develop branch version 3032 to 3039

**Comment by drashti-rydt** [comment]
15-11-2024
==================================================================

2024-11-11 11:38:24.808 +05:30 [ERR] FrmMessage - hUxRykm0J5rcLCA5NrvR - System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: value
   at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value)
   at x4WWNDbaS0ZKmD3Eqdpj.eMtbitKdGGW(Object , Int32 , x4WWNDbaS0ZKmD3Eqdpj )
   at TradingSystem.FrmMessage.wA98WsfTER() in D:\Live\VMD\TradingSystem\TradingSystem\Log\FrmMessage.cs:line 240


Solve This Error

**Comment by Sakshi-Restalgo** [comment]
**Solved this error in the trading system**  -->

-  2024-11-12 12:41:08.753 +05:30 [ERR] frmNetPositionList - kaMXTYO2zbWgSg22BP5C - System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at TradingSystem.frmNetPositionList.<<FrmNetPositionList_Load>b__10_0>d.dQC9amO2tgHugn5ES7R7(Object , Object )
   at TradingSystem.frmNetPositionList.<<FrmNetPositionList_Load>b__10_0>d.MoveNext() in D:\Live\VMD\TradingSystem\TradingSystem\Reports\frmNetPositionList.cs:line 136.

**Status** -- Testing done for my side and merging done with virag sir.

**Comment by VIRAG-RestAlgo** [comment]
> **Solved this error in the trading system** -->
> 
> * 2024-11-12 12:41:08.753 +05:30 [ERR] frmNetPositionList - kaMXTYO2zbWgSg22BP5C - System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
>   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
>   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
>   at TradingSystem.frmNetPositionList.<<FrmNetPositionList_Load>b__10_0>d.dQC9amO2tgHugn5ES7R7(Object , Object )
>   at TradingSystem.frmNetPositionList.<<FrmNetPositionList_Load>b__10_0>d.MoveNext() in D:\Live\VMD\TradingSystem\TradingSystem\Reports\frmNetPositionList.cs:line 136.
> 
> **Status** -- Testing done for my side and merging done with virag sir.

Done and merge in master and develop branch.

**Comment by VIRAG-RestAlgo** [comment]
> **Solved this error in the trading system** -->
> 
> * 2024-11-12 12:41:08.753 +05:30 [ERR] frmNetPositionList - kaMXTYO2zbWgSg22BP5C - System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
>   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
>   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
>   at TradingSystem.frmNetPositionList.<<FrmNetPositionList_Load>b__10_0>d.dQC9amO2tgHugn5ES7R7(Object , Object )
>   at TradingSystem.frmNetPositionList.<<FrmNetPositionList_Load>b__10_0>d.MoveNext() in D:\Live\VMD\TradingSystem\TradingSystem\Reports\frmNetPositionList.cs:line 136.
> 
> **Status** -- Testing done for my side and merging done with virag sir.

Done and merge in master and develop branch.

**Comment by VIRAG-RestAlgo** [comment]
> **Solved this error in the trading system** -->
> 
> * 2024-11-12 12:41:08.753 +05:30 [ERR] frmNetPositionList - kaMXTYO2zbWgSg22BP5C - System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
>   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
>   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
>   at TradingSystem.frmNetPositionList.<<FrmNetPositionList_Load>b__10_0>d.dQC9amO2tgHugn5ES7R7(Object , Object )
>   at TradingSystem.frmNetPositionList.<<FrmNetPositionList_Load>b__10_0>d.MoveNext() in D:\Live\VMD\TradingSystem\TradingSystem\Reports\frmNetPositionList.cs:line 136.
> 
> **Status** -- Testing done for my side and merging done with virag sir.

Done and merge in master and develop branch.

**Comment by VIRAG-RestAlgo** [comment]
> # 15-11-2024
> 2024-11-11 11:38:24.808 +05:30 [ERR] FrmMessage - hUxRykm0J5rcLCA5NrvR - System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: value at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value) at x4WWNDbaS0ZKmD3Eqdpj.eMtbitKdGGW(Object , Int32 , x4WWNDbaS0ZKmD3Eqdpj ) at TradingSystem.FrmMessage.wA98WsfTER() in D:\Live\VMD\TradingSystem\TradingSystem\Log\FrmMessage.cs:line 240
> 
> Solve This Error

Done and merge in master and develop branch.

**Comment by VIRAG-RestAlgo** [comment]
Bug

Strangle 2 - 4 leg isn't open. (ARV) - Done
PriceDiff, Straddle, strangle Side is not proper work. (VMD) - Done
SquerOff with market all in NP issue. (VMD) - Done
Refresh issue in margin. (PPB) - Done
Rule form open slow. (UPM) - Done
Admin : Refresh issue. (PPB) - Done
PriceDiff_IOC noOfLeg 1 and show 3 Leg. (DJK) - Done
exe close automatically. (VMD)

**Comment by VIRAG-RestAlgo** [comment]
exe close automatically. (VMD) - Done (Last 4 to 5 working in live days no complain regarding exe automatically close)
