### ISSUE TITLE
New Development 11-11-2024 with Dubai client.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#536]
[New Development 11-11-2024 with Dubai client.txt](https://github.com/user-attachments/files/17712091/New.Development.11-11-2024.with.Dubai.client.txt)

**Comment by Sakshi-Restalgo** [comment]
**Point no 3** -- MarketWatch rule add while form select. (SKP) -- done for my side.
**Status** -- development done , testing done and  merging pending with @VIRAG-RestAlgo

**Comment by VIRAG-RestAlgo** [comment]
1. In SqureOffPrice logic chagne by Vaibhavbhai today.

* As per buy sell get value from market depth.
* +/- 10 tick as per buy sell.
* after +/- tick if new squreoff price is not in range of DPR then low dpr consider for sell and high dpr consider for buy.

**Comment by Usha-Restalgo** [comment]
Point no 6 -open last added rule -development done 
Testing By VMD is remain

**Comment by VIRAG-RestAlgo** [comment]
NewDevelopment
1. GSet Order Lot Change in deactive rule. (Deactive thay pchi tamare change kari devanu) (VMD) - Pending.
2. Active Rule possible in algo market watch ???? (Client ask 30) (Dipakbhai)
3. MarketWatch rule add while form select. (SKP) - Done
4. Straddle rule market depth required. (possible) (VMD) - Pending
5. Algo Leg (small - capital working proper) (ARV) - Done
6. Last rule open in algo rule form. (UPM) - WIP
7. Only Escap to close this form. (On enter only add rules) (UPM) - Pending
8. Templat all show. (UPM) - Pending
9. Staddle by default ratio 0. (VMD) - Done

**Comment by VIRAG-RestAlgo** [comment]
> 1. In SqureOffPrice logic chagne by Vaibhavbhai today.
> 
> * As per buy sell get value from market depth.
> * +/- 10 tick as per buy sell.
> * after +/- tick if new squreoff price is not in range of DPR then low dpr consider for sell and high dpr consider for buy.

Done

**Comment by drashti-rydt** [comment]
14-11-2024
=======================================================
All Task Development Done in NXBlock Only merging Pending

**Comment by Aman-Restalgo** [comment]
Algo Leg (small - capital working proper) (ARV)-Development Done and merging done

**Comment by VIRAG-RestAlgo** [comment]
Below task allot to @Sakshi-Restalgo 

GSet Order Lot Change in deactive rule. (Deactive thay pchi tamare change kari devanu) @Sakshi-Restalgo

**Comment by Usha-Restalgo** [comment]
Point no 6 and 8 's devlopment is done
Testing And Merging is remain by Virag Bhai

**Comment by VIRAG-RestAlgo** [comment]
Belo Task Allot to @Usha-Restalgo  (Create new branch from VMD_Develop)

Straddle rule market depth required. (possible) (Six depth required maximum) - @Usha-Restalgo

**Comment by Usha-Restalgo** [comment]
Straddle rule market depth required. (possible) (Six depth required maximum) -devlopment done

**Comment by Sakshi-Restalgo** [comment]
GSet Order Lot Change in deactive rule. (Deactive thay pchi tamare change kari devanu) @Sakshi-Restalgo 

Status -- this task is done on 18-11-2024

**Comment by VIRAG-RestAlgo** [comment]
1. GSet Order Lot Change in deactive rule. (Deactive thay pchi tamare change kari devanu) (VMD) - Done.
2. Last rule open in algo rule form. (VMD,UPM) - Done
3. Template all show. (VMD,UPM) - Done

**Comment by VIRAG-RestAlgo** [comment]
@Jill-Restalgo @pratik123c Only below points are pending

NewDevelopment

1. Straddle rule market depth required. (possible) (VMD) - Pending
2. Only Escap to close this form. (On enter only add rules) (UPM) - Pending

**Comment by Usha-Restalgo** [comment]
Straddle rule market depth required. (possible)-development done
Testing and merging by VMD is Remain

**Comment by Usha-Restalgo** [comment]
below is my check point for point no 6
[536-point no 6-Last rule open in algo rule form.pdf](https://github.com/user-attachments/files/17973895/536-point.no.6-Last.rule.open.in.algo.rule.form.pdf)

**Comment by VIRAG-RestAlgo** [comment]
> [@Jill-Restalgo](https://github.com/Jill-Restalgo) [@pratik123c](https://github.com/pratik123c) Only below points are pending
> 
> NewDevelopment
> 
> 1. Straddle rule market depth required. (possible) (VMD) - Pending
> 2. Only Escap to close this form. (On enter only add rules) (UPM) - Pending

Above two points are pending.

**Comment by Usha-Restalgo** [comment]
Only Escap to close this form. (On enter only add rules) (UPM) -Development done 
Testing and merging is remain @VIRAG-RestAlgo

**Comment by Usha-Restalgo** [comment]
Straddle rule market depth required. (possible) (VMD) - development done
Testing and merging is remain @VIRAG-RestAlgo

**Comment by Usha-Restalgo** [comment]
**11-12--2024**
Merging task no 536 point no 7 with virag sir
testing and code changing in Algomarketwatch  Ascending and descding

**Comment by VIRAG-RestAlgo** [comment]
> NewDevelopment
> 
> 1. GSet Order Lot Change in deactive rule. (Deactive thay pchi tamare change kari devanu) (VMD) - Pending.
> 2. Active Rule possible in algo market watch ???? (Client ask 30) (Dipakbhai)
> 3. MarketWatch rule add while form select. (SKP) - Done
> 4. Straddle rule market depth required. (possible) (VMD) - Pending
> 5. Algo Leg (small - capital working proper) (ARV) - Done
> 6. Last rule open in algo rule form. (UPM) - WIP
> 7. Only Escap to close this form. (On enter only add rules) (UPM) - Pending
> 8. Templat all show. (UPM) - Pending
> 9. Staddle by default ratio 0. (VMD) - Done

Point No. 7 merged in main branch.

**Comment by VIRAG-RestAlgo** [comment]
> > [@Jill-Restalgo](https://github.com/Jill-Restalgo) [@pratik123c](https://github.com/pratik123c) Only below points are pending
> > NewDevelopment
> > 
> > 1. Straddle rule market depth required. (possible) (VMD) - Pending
> > 2. Only Escap to close this form. (On enter only add rules) (UPM) - Pending
> 
> Above two points are pending.

Both Points are done and deploy now. Task Completed.

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo pdf upload for Sr.No. 4 and 7

**Comment by Usha-Restalgo** [comment]
pdf for Straddle rule market depth required. (possible) TaskID 536 Sr. No. 4 is below[536_4 Straddle rule market depth required..pdf](https://github.com/user-attachments/files/18135291/536_4.Straddle.rule.market.depth.required.pdf)

**Comment by Usha-Restalgo** [comment]
pdf for point no 7 on only esc close the form is below

[536_7 only on esc close the form.pdf](https://github.com/user-attachments/files/18135301/536_7.only.on.esc.close.the.form.pdf)
