### ISSUE TITLE
Error 13-11-2024 With Dubai client

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#537]
1. Algomarket watch L4StrikePrice required in decimal .00 @Aman-Restalgo 
2. Disparity issue in Strangle (Solution is : Average by strike price and sum of average of strike price) @VIRAG-RestAlgo 
3. One time happed in straddle rule FS RS not update, after re-login FS RS is update. @VIRAG-RestAlgo 
4. SequreOff  not working from net position both option even by enter form is open but squreOff not done. @VIRAG-RestAlgo 
5. Margin didn't release on trade. @pratik-restalgo 
6. Margin/M2M hit but sequreOff didn't work. @pratik-restalgo 
7. RuleWise net position some time stuck and exe close, this issue find by VMD on date 13-11-2024. @Anil-Restalgo

**Comment by VIRAG-RestAlgo** [comment]
RuleWise net position some time stuck and exe close, this issue find by VMD on date 13-11-2024. @Anil-Restalgo - Done and Check by VMD and merge in master and develop branch.

This is deploy today.

**Comment by VIRAG-RestAlgo** [comment]
1. Algomarket watch L4StrikePrice required in decimal .00 @Aman-Restalgo - Done
2. Disparity issue in Strangle (Solution is : Average by strike price and sum of average of strike price) @VIRAG-RestAlgo - Done
3. One time happed in straddle rule FS RS not update, after re-login FS RS is update. @VIRAG-RestAlgo - Done (This cast completely understand with Dipakbhai.)
4. SequreOff not working from net position both option even by enter form is open but squreOff not done. @VIRAG-RestAlgo - Done
5. Margin didn't release on trade. @pratik-restalgo
6. Margin/M2M hit but sequreOff didn't work. @pratik-restalgo
7. RuleWise net position some time stuck and exe close, this issue find by VMD on date 13-11-2024. @Anil-Restalgo - Done

**Comment by VIRAG-RestAlgo** [comment]
@Jill-Restalgo @pratik123c Only below points are pending

1. Margin didn't release on trade. @pratik-restalgo
2. Margin/M2M hit but sequreOff didn't work. @pratik-restalgo

**Comment by pratik-restalgo** [comment]
@Jill-Restalgo @pratik123c  Below points are done and update in live. Please check and update here if not done.

1. Margin didn't release on trade. 
2. Margin/M2M hit but sequreOff didn't work.
