### ISSUE TITLE
Error 14-11-2024 With Dubai client

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#542]
1. By Change Symbol Lot size or any hidden contract details update. @Usha-Restalgo 
2. Straddle FS-RS not update while exe re-login. @VIRAG-RestAlgo

**Comment by VIRAG-RestAlgo** [comment]
Straddle FS-RS not update while exe re-login. @VIRAG-RestAlgo - Done

**Comment by Usha-Restalgo** [comment]
By Change Symbol Lot size or any hidden contract details update.-devlopment done

**Comment by VIRAG-RestAlgo** [comment]
1. By Change Symbol Lot size or any hidden contract details update. @Usha-Restalgo 
2. Straddle FS-RS not update while exe re-login. @VIRAG-RestAlgo  - Done

**Comment by Usha-Restalgo** [comment]
By Change Symbol Lot size or any hidden contract details update-testing done by VMD
Development merged to  Anilbhai @Anil-Restalgo

**Comment by Usha-Restalgo** [comment]
Below is my check point for point no 
1
[542-lotsize and ticksize set to teztbox.pdf](https://github.com/user-attachments/files/17973571/542-lotsize.and.ticksize.set.to.teztbox.pdf)

**Comment by VIRAG-RestAlgo** [comment]
> Below is my check point for point no 1 [542-lotsize and ticksize set to teztbox.pdf](https://github.com/user-attachments/files/17973571/542-lotsize.and.ticksize.set.to.teztbox.pdf)

Sr. No. 1 - Done and deploy now. @Jill-Restalgo and @pratik123c
