### ISSUE TITLE
Dubai -> Add four columns in algo marketwatch

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#547]
As discussed with Vaibhavbhai and Lokeshsir add following columns in algo MarketWatch.

1. M2M
2. RuleNetLot
3. F-ATP
4. R-ATP

**Comment by VIRAG-RestAlgo** [comment]
Development done for following columns are added in algo MarketWatch. (Deployment done for UAT) @Jill-Restalgo and @pratik123c 

1. M2M
2. RuleNetLot

**Comment by VIRAG-RestAlgo** [comment]
Above two column testing ok by Dipakbhai and deploy in live. code merged in master and develop branch,.

**Comment by VIRAG-RestAlgo** [comment]
@Jill-Restalgo  and @pratik123c please confirm for two column M2M and RuleNetLot columns.

**Comment by pratik123c** [comment]
1. M2M
2. RuleNetLot
   It is ok and work properly

**Comment by VIRAG-RestAlgo** [comment]
> 1. M2M
> 2. RuleNetLot
>    It is ok and work properly

Ok Thanks

**Comment by VIRAG-RestAlgo** [comment]
> As discussed with Vaibhavbhai and Lokeshsir add following columns in algo MarketWatch.
> 
> 1. M2M
> 2. RuleNetLot
> 3. F-ATP
> 4. R-ATP

3. F_ATP and
4. R_ATP development done.

**Comment by Anil-Restalgo** [comment]
[T547. Dubai - Add four columns in algo marketwatch..pdf](https://github.com/user-attachments/files/22077762/T547.Dubai.-.Add.four.columns.in.algo.marketwatch.pdf)
