### ISSUE TITLE
Dubai -> Cycle wise disparity show.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#554]
Dubai -> Cycle wise disparity show.[Cycle wise Disparity.xlsx](https://github.com/user-attachments/files/17988752/Cycle.wise.Disparity.xlsx)

Please start work as discuss today.

**Comment by Anil-Restalgo** [comment]
As per Discuss With VaibhavBhai Today.

FW and RW-REV - Blue 
RW and FW-REV - Red

**Comment by Anil-Restalgo** [comment]
1) Creating a Report of CycleWiseATP.
2) Apply All Properties In This .
3) Report Data Save
      bin  format
4) Report Data Load (CurrentDayFile as per order book tradebook)
      bin format
5) Rule Delete
      No Change
6) Every Day new file create for save and load
7) If cycle complete then ActualFSRS show other wise 0.00
8) TokenNumber with ExecutedQty show like 35001 (15)
9) Proper Log (information , fatal , debug)
10) try catch
11) All added in RuleNumber filter.
12) Check All Try Catch and Logd and Add All of This and Do Comment Also.
13) Correction Done Regarding Sign Issue While REV.
14) Changes in Strangle_FS and Strangle_RS With VMD by APN on (17-12-2024).
15) Complete in PriceDiff,ButterFly,Strangle and Straddle Strategy.
16) Open CycleWiseATP Form  by "C" from AlgoMarketWatch From Grid by AnyRule.

**Till Date Complete All Above Point in This Report.**

**Comment by VIRAG-RestAlgo** [comment]
[CycleWiseATP-Diff.xlsx](https://github.com/user-attachments/files/18208782/CycleWiseATP-Diff.xlsx)

Diff column calculation.

**Comment by Anil-Restalgo** [comment]
Complete All Strategy in FSRS.

**Comment by Anil-Restalgo** [comment]
[T554 Cycle wise disparity show..pdf](https://github.com/user-attachments/files/18217597/T554.Cycle.wise.disparity.show.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Deployment done.
