### ISSUE TITLE
Dubai -> New Development 03-12-2024

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#556]
Dubai -> New Development 03-12-2024

03-12-2024 | In Butter Fly Strategy,  - By   Default Ratio 2 in 2nd Leg. | SKP | New Development
03-12-2024 | In Box, Driver leg field open in all leg. | SKP | New Development
03-12-2024 | In Box, If all leg driver No then any next one will Driver Yes | SKP | New Development

**Comment by VIRAG-RestAlgo** [comment]
03-12-2024 | In Butter Fly Strategy, - By Default Ratio 2 in 2nd Leg. | SKP | New Development - Done and Deployment Done
03-12-2024 | In Box, Driver leg field open in all leg. | SKP | New Development - Done and Deployment Done

**Comment by Sakshi-Restalgo** [comment]
All point done for my side.

**Comment by Sakshi-Restalgo** [comment]
below is my T556 checkpoint please check and review that
[CheckPoint - TaskId-556.pdf](https://github.com/user-attachments/files/18034121/CheckPoint.-.TaskId-556.pdf)

**Comment by VIRAG-RestAlgo** [comment]
@Sakshi-Restalgo please merge this point tomorrow 

03-12-2024 | In Box, If all leg driver No then any next one will Driver Yes | SKP | New Development

**Comment by VIRAG-RestAlgo** [comment]
> [@Sakshi-Restalgo](https://github.com/Sakshi-Restalgo) please merge this point tomorrow
> 
> 03-12-2024 | In Box, If all leg driver No then any next one will Driver Yes | SKP | New Development

Code merged in master branch.
