### ISSUE TITLE
Dubai -> 1st Leg Value not update in other leg while algo rule load by old save rule or template

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#560]
Dubai -> 1st Leg Value not update in other leg while algo rule load by old save rule or template

This changes has been confirm with Dhruvinbhai also.

**Comment by Sakshi-Restalgo** [comment]
Development done - testing wip.

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo we have test but not correct yet so please check with @Sakshi-Restalgo  and complete task tomorrow.

**Comment by Sakshi-Restalgo** [comment]
After identifying the bugs, they were resolved, development was completed, and proper testing was done. When I was testing, Virag Sir also reviewed it.

**Comment by Sakshi-Restalgo** [comment]
merging pending with virag sir

**Comment by VIRAG-RestAlgo** [comment]
@Sakshi-Restalgo please update check point.

**Comment by Sakshi-Restalgo** [comment]
below is my T560 checkpoint please check and review that
[CheckPoint- 560.pdf](https://github.com/user-attachments/files/18096436/CheckPoint-.560.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Task merged in master branch.

**Comment by VIRAG-RestAlgo** [comment]
@Jill-Restalgo  @pratik123c please note this task revert by Dhruvinbhai and Dipakbhai.

right now this is not required.

**Comment by VIRAG-RestAlgo** [comment]
> [@Jill-Restalgo](https://github.com/Jill-Restalgo) [@pratik123c](https://github.com/pratik123c) please note this task revert by Dhruvinbhai and Dipakbhai.
> 
> right now this is not required.

Deployment Done.
