### ISSUE TITLE
Add New field in algo rule form SpreadType

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#567]
Add New field in algo rule form.

Name : SpreadType 
Value : 1. Driver 2. All

This field never change.
This field show in grid.

@Sakshi-Restalgo if you required any help then you can ask to @Usha-Restalgo

**Comment by VIRAG-RestAlgo** [comment]
SpreadType added in model.

**Comment by VIRAG-RestAlgo** [comment]
@Sakshi-Restalgo  please update checkpoints

**Comment by Sakshi-Restalgo** [comment]
below is my T567 checkpoint please check and review that
[CheckPoint - 567.pdf](https://github.com/user-attachments/files/18096369/CheckPoint.-.567.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Merged in master branch,.
