### ISSUE TITLE
Log write user wise

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#572]
Log write user wise.

1. Before login log write in common (current path)
2. After login log write in user folder.

Before start this task please discuss.

**Comment by Sakshi-Restalgo** [comment]
Deployment done ,testing done and merging done with virag sir.

Below is my T11 checkpoint please check and review that.
[CheckPoint - Task ID 572.pdf](https://github.com/user-attachments/files/18149062/CheckPoint.-.Task.ID.572.pdf)

**Comment by VIRAG-RestAlgo** [comment]
This task merged in main branch.
