### ISSUE TITLE
Error in algo marketwatch

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#577]
![Image](https://github.com/user-attachments/assets/a82969e8-c7e9-4aec-a8d1-9edab5ca57f1)

**Comment by Sakshi-Restalgo** [comment]
Development done ,and testing done for my side.

**Comment by Sakshi-Restalgo** [comment]
Testing and merging pending with virag sir

**Comment by Sakshi-Restalgo** [comment]
Below is my T577 checkpoint please check and review that.
[CheckPoint - Task 577.pdf](https://github.com/user-attachments/files/18148932/CheckPoint.-.Task.577.pdf)

**Comment by VIRAG-RestAlgo** [comment]
This task merged merge in main branch.
