### ISSUE TITLE
Template contract data update.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#579]
While exe login first time at that time Template contract data update.

**Comment by Sakshi-Restalgo** [comment]
Development done ,testing done for my side and testing , merging pending with virag sir.

**Comment by Sakshi-Restalgo** [comment]
Below is my T579 checkpoint please check and review that.
[CheckPoint -Task id -- 579.pdf](https://github.com/user-attachments/files/18181286/CheckPoint.-Task.id.--.579.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Task merged in main branch.
