### ISSUE TITLE
Trade book orders need to be shown in Descending order.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#58]
Last trade traded order to be shown at the top row, then 2nd last trade in 2nd row and so on.

**Comment by VIRAG-RestAlgo** [comment]
you need to set reverse trade book row on screen.
you have to add trade book row in last. this can manage at the time of add row in main memory.

if required any help please ask to @Anil-Restalgo

**Comment by Sakshi-Restalgo** [comment]
As per discuss with Virag sir

**Comment by Anil-Restalgo** [comment]
[T58 Trade book orders need to be shown in Descending order..pdf](https://github.com/user-attachments/files/16357165/T58.Trade.book.orders.need.to.be.shown.in.Descending.order.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done. This logic work with Lokeshsir and APN.
this logic merged in live trading exe and given for testing to Dipakbhai.
