### ISSUE TITLE
While Order square off by netposition at time price not get as per order pref. price protection.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#587]
While Order square off by netposition at time price not get as per order pref. price protection.

**Comment by Anil-Restalgo** [comment]
[T587 While Order square off by netposition at time price not get as per order pref. price protection...pdf](https://github.com/user-attachments/files/18217596/T587.While.Order.square.off.by.netposition.at.time.price.not.get.as.per.order.pref.price.protection.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Deployment done.
