### ISSUE TITLE
T000003: Trade Book / Order Book export to csv.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#6]
Create template for Trade Book / Order Book reports to export to .csv file and export csv file for Order Book / Trade Book by selecting template.

1. Create template by entering template name and type (Order Book / Trade Book)
2. Select fields from available columns for Trade Book / Order Book.
3. User can select custom format for each selected field.
4. Save template
5. Add option to export data from Order Book / Trade Book from context menu and display respective templates created by user in save dialog box.

![Image](https://github.com/RestAlgo/TradingApplication/assets/168447176/e34e5a04-16b4-4519-9318-e80fbe8bba93)
![Image](https://github.com/RestAlgo/TradingApplication/assets/168447176/7547f86c-6494-46c5-96de-17099f60dff6)
![Image](https://github.com/RestAlgo/TradingApplication/assets/168447176/40164a2b-05f3-47ef-9040-06b41c729799)
![Image](https://github.com/RestAlgo/TradingApplication/assets/168447176/308dc706-789a-4747-8338-43e0b18a9af5)
![Image](https://github.com/RestAlgo/TradingApplication/assets/168447176/a722a4a8-055f-41d5-b7de-52d66d7a6940)
![Image](https://github.com/RestAlgo/TradingApplication/assets/168447176/36dd6c4a-f27d-4a21-a980-62ef13aa4927)
![Image](https://github.com/RestAlgo/TradingApplication/assets/168447176/2b97bd8d-81da-41fb-a2cd-8fced4c15485)

**Comment by Sakshi-Restalgo** [comment]
Development in frmFileFormatDataTransfer and frmCreateFileFormat.
1-Create template by entering template name and type (Order Book / Trade Book) --development done.
2-In the template, select 'orderbook' or 'trade book' from the type, and then load the column names in the data transfer from the file 
    format.----development done.
3-Select the columns from the Order book/Trade book and add them to the fields.--development done.
4-User can select custom format for each selected field.--development done.
5 -Save template.--development done.
5-Add option to export data from Order Book / Trade Book from context menu and display respective templates created by user in save dialog box.--development done.

**Comment by Sakshi-Restalgo** [comment]
[CheckPoint-TradeBookOrderBookExportToCSV.pdf](https://github.com/RestAlgo/TradingApplication/files/15452376/CheckPoint-TradeBookOrderBookExportToCSV.pdf)

**Comment by Sakshi-Restalgo** [comment]
Server is not connected is pending work in try to local.

**Comment by Sakshi-Restalgo** [comment]
Testing Pending  with Lokesh Sir

**Comment by Sakshi-Restalgo** [comment]
Development Done For template for Trade Book / Order Book reports to export to .csv file and export csv file for Order Book / Trade Book by selecting template.
Testing pending

**Comment by Sakshi-Restalgo** [comment]
Development Done For template for Trade Book / Order Book reports to export to .csv file.

[CheckPoint-OrderBook_TradeBook_CSV.pdf](https://github.com/user-attachments/files/16156134/CheckPoint-OrderBook_TradeBook_CSV.pdf)
