### ISSUE TITLE
Net Position ma Right click par square off option hovu joiye.

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#60]

**Comment by VIRAG-RestAlgo** [comment]
@Kartik-RestAlgo  please check this task is already done another task id so please update you task.

**Comment by Kartik-RestAlgo** [comment]
This Task is Already Done in Task 95 and Branch is KAR_T95

**Comment by VIRAG-RestAlgo** [comment]
Done
