### ISSUE TITLE
Check "Check All" options while save in "Exchange Permission" tab in User Master

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#65]
"Check All" option is saved in database. It should not be saved.

**Comment by Aman-Restalgo** [comment]
It seems like you had to implement a new view and write some new code for it, but the code was getting too lengthy using the previous approach. Therefore, you opted for a different method to achieve it.

[T_65_CheckPoint_TradingSystem_21-05-2024.pdf](https://github.com/RestAlgo/TradingApplication/files/15384657/T_65_CheckPoint_TradingSystem_21-05-2024.pdf)
