### ISSUE TITLE
Check password reset issue in Trading Application and Admin Module

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#66]
When password is reset and re-login, User disconnected message displayed and login form is not closed and login to application is done successfully. Check in both Admin Module and Trading Application.

**Comment by pratik-restalgo** [comment]
Done in Admin Module. Pending in Trading Application.

**Comment by Aman-Restalgo** [comment]
Attached Checkpoints.

[T_66_CheckPoint_TradingSystem_21-05-2024.pdf](https://github.com/RestAlgo/TradingApplication/files/15384608/T_66_CheckPoint_TradingSystem_21-05-2024.pdf)

**Comment by VIRAG-RestAlgo** [comment]
In Trading Application Done
