### ISSUE TITLE
Normal Market Depth

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#68]
@Usha-Restalgo  

As per ATINS normal marketwatch depth should be work in our trading application.

All field should be updated.

While token change then it should be subscribe and all data should be show on screen at a time.

We have already discuss then after if you have any query please ask to me.

**Comment by VIRAG-RestAlgo** [comment]
Done

**Comment by Usha-Restalgo** [comment]
[68-MarketDepth.pdf](https://github.com/user-attachments/files/16408981/68-MarketDepth.pdf)
