### ISSUE TITLE
Insert DB Log

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#79]
Create new table for database table insert/update/delete log, create new SP to insert log in log table.
SP and table structure will be provided.

Call SP in every SP in which any DML statement is written.
SP call sample:

SET @key1 = @SrNo

		DECLARE @xmldata AS XML
		SET @xmldata = (SELECT *
						FROM UserMaster
						WHERE SrNo = @SrNo
						FOR XML AUTO, ROOT ('Log'))

		EXEC dbo.RI_InserLogTable 'UserMaster', -- Table name
								   @key1, --Key data 1
								   '', --Key data 2
								   '', --Key data 3
								   @xmldata, -- Row xml data
								   'DELETE', -- Mode (Insert, Update, Delete)
								   @UserID, -- Entry UserID
								   @ModifiedTime, -- Entry Date
								   @IPAddress -- Entry Date

Pass IP Address in SP from API if not passed.

**Comment by Aman-Restalgo** [comment]
some chenges after testing

**Comment by Aman-Restalgo** [comment]
almost done but limit log is pending because of discussion pending with  ppb

**Comment by Aman-Restalgo** [comment]
Done

**Comment by VIRAG-RestAlgo** [comment]
@Aman-Restalgo    send me Check point.

**Comment by Aman-Restalgo** [comment]
Checkpoint

[T_79_CheckPoint_AdminModule_08-06-2024.pdf](https://github.com/user-attachments/files/15756677/T_79_CheckPoint_AdminModule_08-06-2024.pdf)
