### ISSUE TITLE
In Algo Rule Add strategy name Stradle and leg no 1

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#82]
Add one strategy as Stradle and no. of leg value 1.

No. of leg value can't changed by any one if strategy is Stradle.

1 leg show in algo rule.

**Comment by VIRAG-RestAlgo** [comment]
Development Done

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo send checkpoint

**Comment by Usha-Restalgo** [comment]
below is my checkpoint for task no 82 
please check and review that


[90&82 Straddle Logic.pdf](https://github.com/user-attachments/files/15603312/90.82.Straddle.Logic.pdf)

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo  this task  will check and merge when we merged Task ID 345

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo and @Aman-Restalgo this task move to InProcess due to we need to convert this logic in to dynamic concept which is instruction given by Lokeshsir.

**Comment by Usha-Restalgo** [comment]
task is developed as per discussion and instruction so putting this task to development done

**Comment by VIRAG-RestAlgo** [comment]
Done
