### ISSUE TITLE
Algo Rule Generate for Straddle Strategy.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#90]
Base On Task Sr.# 72

Add Straddle strategy in Algo rule with one leg.

Validation : if Strategy name Straddle then No of leg should be 1.

**Comment by Usha-Restalgo** [comment]
This task's development done tomorrow on date 16-05-2024 
Testing is remain by VMD

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo   send me Check point.

**Comment by Usha-Restalgo** [comment]
below is my checkpoint of task no 90 


[90&82 Straddle Logic.pdf](https://github.com/user-attachments/files/15603305/90.82.Straddle.Logic.pdf)

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo  this task  will check and merge when we merged Task ID 345

**Comment by VIRAG-RestAlgo** [comment]
@Usha-Restalgo  and @Aman-Restalgo this task move to InProcess due to we need to convert this logic in to dynamic concept which is instruction given by Lokeshsir.

**Comment by Usha-Restalgo** [comment]
task is developed as per discussion and instruction so putting this task to development done

**Comment by Usha-Restalgo** [comment]
as per discussion doing change in logic

**Comment by Usha-Restalgo** [comment]
change is done as per discussed so putting this task to development  done

**Comment by VIRAG-RestAlgo** [comment]
Done
