### ISSUE TITLE
NetPosition Form Correction

### ISSUE THREAD

**Issue by lokesh-rydt** [RestAlgo/TradingApplication#95]
Alt + F6, Create always new window for NetPosition

On NetPosition KeyPress (+ / -) OR (F1 / F2) -> Order Entry From to open, similar to F5
On NetPosition KeyPress (ENTER) -> Order SQ. option means if NetQty is 5 on Buy Side then Sell Order Entry From open with 5 qty and vice a versa

Right Click, Provide "Square Up with Market" option and ask confirmation dialog if Yes -> Auto sq order to send
"Do you want to Square Up at Market?", YES / NO, => Defaukt NO

Right Click, Provide "Square Up All with Market" option and ask confirmation dialog if Yes -> Auto sq order to send
"Do you want to Square All at Market?", YES / NO, => Defaukt NO

Filter Option
1. Client / Dealer -> Distinct ClientCode and DealerCode (from NetPosition) with All option, === Default ALL
2. Expiry -> Expiry (Display single line for Day+Opening), Day, Opening, ==== Default EXPIRY
3. Exchange (from NetPosition) === Default ALL
4. Instrument (from NetPosition) === Default ALL
5. Symbol (from NetPosition) === Default ALL
6. Expiry (from NetPosition) === Default ALL
7. Option (from NetPosition) === Default ALL
8. StrikePrice (from NetPosition) === Default ALL
9. Token (To Remove)
10. Product, (from NetPosition) === Default ALL

At the end, Total Row to create (NetQty, M2M, NetAvg, BuyQty, SellQty, ByuValue, Sellvalue, Netvalue)

Show Button to Remove and Filter Grid with Change DropDown

CLIENT, DEALER, Token, PRODUCT Group wise row display

No of columns as per current list, keep as it is
*** Add New Column TradeFlag (Day, Opening)

*** if Filter is Day/Opening, and Sq order action is given, and if Day + Opening is ZERO then just show Confirm Dialog
"This sysbol is already square up against Day/Opening, Are you sure to Square Up?", YES / NO, => Defaukt NO
============

Right Click, Provide "Copy to clipboard" 
Right Click, Provide "Copy to Excel"

**Comment by Usha-Restalgo** [comment]
check filter and make changes as per requirement 
Show Button to Remove and Filter Grid with Change DropDown
CLIENT, DEALER, Token, PRODUCT Group wise row display
Add New Column TradeFlag (Day, Opening)
if Filter is Day/Opening, and Sq order action is given, and if Day + Opening is ZERO then just show Confirm Dialog
"This symbol is already square up against Day/Opening, Are you sure to Square Up?", YES / NO, => Default NO by ME and Kartik bhai
At the end, Total Row to create (NetQty, M2M, NetAvg, BuyQty, SellQty, ByuValue, Sellvalue, Netvalue)-checked

So i am sending this task to devlopment Done

**Comment by Kartik-RestAlgo** [comment]
Square up with Market - selected row netqty will be Squareup & 
Square up all with Market - all record in NetPosition wii be Square Off all done.

**Comment by Kartik-RestAlgo** [comment]
Alt + F6, Create always new window for NetPosition update is Pending So move to In Progress

**Comment by Kartik-RestAlgo** [comment]
NetPosition is opening multiple time done

**Comment by Kartik-RestAlgo** [comment]
[NetPosition Form Correction.pdf](https://github.com/RestAlgo/TradingApplication/files/15385334/NetPosition.Form.Correction.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Code testing is in process.

**Comment by VIRAG-RestAlgo** [comment]
Output 

Alt + F6, Create always new window for NetPosition -> **OK**

On NetPosition KeyPress (+ / -) OR (F1 / F2) -> Order Entry From to open, similar to F5 -> **OK**

On NetPosition KeyPress (ENTER) -> Order SQ. option means if NetQty is 5 on Buy Side then Sell Order Entry From open with 5 qty and vice a versa -> **OK**

Right Click, Provide "Square Up with Market" option and ask confirmation dialog if Yes -> Auto sq order to send
"Do you want to Square Up at Market?", YES / NO, => Default NO -> **OK**

Right Click, Provide "Square Up All with Market" option and ask confirmation dialog if Yes -> Auto sq order to send
"Do you want to Square All at Market?", YES / NO, => Default NO -> **OK**

Filter Option

1.     Client / Dealer -> Distinct ClientCode and DealerCode (from NetPosition) with All option, === Default ALL -> **OK**
2.     Expiry -> Expiry (Display single line for Day+Opening), Day, Opening, ==== Default EXPIRY -> **Logic added, Testing Pending by UPM and KAR**
3.     Exchange (from NetPosition) === Default ALL -> **OK**
4.     Instrument (from NetPosition) === Default ALL -> **OK**
5.     Symbol (from NetPosition) === Default ALL -> **OK**
6.     Expiry (from NetPosition) === Default ALL -> **OK**
7.     Option (from NetPosition) === Default ALL -> **OK**
8.     StrikePrice (from NetPosition) === Default ALL -> **OK**
9.     Token (To Remove) -> **OK**
10.     Product, (from NetPosition) === Default ALL -> **OK** New Added


At the end, Total Row to create (NetQty, M2M, NetAvg, BuyQty, SellQty, BuyValue, Sellvalue, Netvalue) -> **OK**

Show Button to Remove and Filter Grid with Change DropDown -> **OK**

CLIENT, DEALER, Token, PRODUCT Group wise row display -> **OK**

No of columns as per current list, keep as it is
*** Add New Column TradeFlag (Day, Opening) ->  **Only Day Show rightnow -> OK**

*** if Filter is Day/Opening, and Sq order action is given, and if Day + Opening is ZERO then just show Confirm Dialog
"This symbol is already square up against Day/Opening, Are you sure to Square Up?", YES / NO, => Default NO -> **[Testing pending]**

**Comment by VIRAG-RestAlgo** [comment]
Now Logic review is started.

**Comment by VIRAG-RestAlgo** [comment]
Logic 

Alt + F6, Create always new window for NetPosition -> **OK**

On NetPosition KeyPress (+ / -) OR (F1 / F2) -> Order Entry From to open, similar to F5 -> **OK**
On NetPosition KeyPress (ENTER) -> Order SQ. option means if NetQty is 5 on Buy Side then Sell Order Entry From open with 5 qty and vice a versa -> **OK**

Right Click, Provide "Square Up with Market" option and ask confirmation dialog if Yes -> Auto sq order to send
"Do you want to Square Up at Market?", YES / NO, => Defaukt NO -> **OK**

Right Click, Provide "Square Up All with Market" option and ask confirmation dialog if Yes -> Auto sq order to send
"Do you want to Square All at Market?", YES / NO, => Defaukt NO -> **OK**

Filter Option

    1. Client / Dealer -> Distinct ClientCode and DealerCode (from NetPosition) with All option, === Default ALL -> **OK**
    2. Expiry -> Expiry (Display single line for Day+Opening), Day, Opening, ==== Default EXPIRY -> **OK**
    3. Exchange (from NetPosition) === Default ALL -> **OK**
    4. Instrument (from NetPosition) === Default ALL -> **OK**
    5. Symbol (from NetPosition) === Default ALL -> **OK**
    6. Expiry (from NetPosition) === Default ALL -> **OK**
    7. Option (from NetPosition) === Default ALL -> **OK**
    8. StrikePrice (from NetPosition) === Default ALL -> **OK**
    9. Token (To Remove) -> **OK**
    10. Product, (from NetPosition) === Default ALL -> **OK**
    11. At the end, Total Row to create (NetQty, M2M, NetAvg, BuyQty, SellQty, BuyValue, Sellvalue, Netvalue) -> **OK**

Show Button to Remove and Filter Grid with Change DropDown -> **OK**

CLIENT, DEALER, Token, PRODUCT Group wise row display -> **OK**

No of columns as per current list, keep as it is
*** Add New Column TradeFlag (Day, Opening) -> **OK**

*** if Filter is Day/Opening, and Sq order action is given, and if Day + Opening is ZERO then just show Confirm Dialog
"This sysbol is already square up against Day/Opening, Are you sure to Square Up?", YES / NO, => Defaukt NO --> **Logic Check & Ok, Testing Pending due to open netposition is not found in current system.**

**Comment by VIRAG-RestAlgo** [comment]
Start process to merge

**Comment by VIRAG-RestAlgo** [comment]
due to urgency Unit test unable code is not addressed. day after some time it will convert in to unit test enable code by @Kartik-RestAlgo

**Comment by VIRAG-RestAlgo** [comment]
In NXBlog Algo Order send so now stared merging code

**Comment by VIRAG-RestAlgo** [comment]
As per my logic comments this task has been merged in live exe yesterday.
