### ISSUE TITLE
Straddle FS RS Logic

### ISSUE THREAD

**Issue by lokesh-rydt** [RestAlgo/TradingApplication#96]
Calculation Logic for FS RS for the Straddle Stratagy

[Stradle FS RS.xlsx](https://github.com/RestAlgo/TradingApplication/files/15330954/Stradle.FS.RS.xlsx)

Please also take care to display the FS RS at Client Application with Diff. Stratagy ,i.e. Price Diff and Straddle

**Comment by VIRAG-RestAlgo** [comment]
This task done in decided time.
