### ISSUE TITLE
In NSEFO, Disclosed Qty should be disable.

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#97]
As per instruction given by Vaibhavbhai, In NSEFO, Disclosed Qty should be disable in normal buy and normal sell.

**Comment by Kartik-RestAlgo** [comment]
While Form initialize (frmNormalBuy/ frmNormalSell) is exchange is NSEFO than disclose quantity textbox will disable

**Comment by Kartik-RestAlgo** [comment]
This Task is merge with KAR_T7_14-05-2024

**Comment by Kartik-RestAlgo** [comment]
![Image](https://github.com/RestAlgo/TradingApplication/assets/168506537/82c54dc7-9a42-4679-99a8-fbbd0414b3f8)
![Image](https://github.com/RestAlgo/TradingApplication/assets/168506537/c2bd3d94-339d-42cf-bbe9-778be91c6523)

**Comment by Kartik-RestAlgo** [comment]
[When Exchange is NSEFO than disclose quantity textbox will disable.pdf](https://github.com/RestAlgo/TradingApplication/files/15385344/When.Exchange.is.NSEFO.than.disclose.quantity.textbox.will.disable.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done,.

**Comment by VIRAG-RestAlgo** [comment]
Version : VMD_V24_NormalBuySell
