### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#98]
Installation in In house server (sql and all exe)

Installation in In Delhi server (sql and all exe)

**Comment by Anil-Restalgo** [comment]
Due to server speed low it is taken to much time to installation.  Installation in In house server (sql and all exe) this Point is Done.
Installation in In Delhi server (sql and all exe) Sql server Installation Complete and database import succesfully and All exe installation pending.

**Comment by VIRAG-RestAlgo** [comment]
@Anil-Restalgo please update latest status. all clients.

**Comment by Anil-Restalgo** [comment]
(192.168.0.36) in this server Install SQL Server DataBase Installation Done And DataBase SuccessFully Import in this Server In this Server IIS Installation Done IIS API Host Import Successfully.In This Server Admin Module EXE Done Client Trading System EXE Done Algo Spinner Exe Done FileDownload Exe Done NSEFO Delegate EXE Done RYDT Ops Engine EXE Done And BroadCast Also Done. In This Server All Installation Done.

**Comment by Anil-Restalgo** [comment]
(NXBLOG(Delhi)) in  this server SQL server installation Done And DataBase Import Successfully. And then All Exe and IIS Installation Pending.

**Comment by Anil-Restalgo** [comment]
(Anisha(Delhi)) in  this server SQL server installation Done And DataBase Import Successfully. And then All Exe and IIS Installation Pending.

**Comment by Anil-Restalgo** [comment]
[Status of client Installation.xlsx](https://github.com/RestAlgo/TradingApplication/files/15373546/Status.of.client.Installation.xlsx)

**Comment by Anil-Restalgo** [comment]
(Anisha(Delhi))  In this Server IIS Installation Done IIS API Host Import Successfully.In This Server Admin Module EXE Done Client Trading System EXE Done Algo Spinner Exe Done FileDownload Exe Done RYDT Ops Engine EXE Done And BroadCast Also Pending. NSEFO Delegate EXE Pending.

**Comment by Anil-Restalgo** [comment]
[Status of client Installation.xlsx](https://github.com/RestAlgo/TradingApplication/files/15377386/Status.of.client.Installation.xlsx)

**Comment by Anil-Restalgo** [comment]
(192.168.0.36) in this server Install SQL Server DataBase Installation Done And DataBase SuccessFully Import in this Server In this Server IIS Installation Done IIS API Host Import Successfully.In This Server Admin Module EXE Done Client Trading System EXE Done Algo Spinner Exe Done FileDownload Exe Done NSEFO Delegate EXE Done RYDT Ops Engine EXE Done And BroadCast Also Done. In This Server All Installation Done. On Live Server and NSEFO Delegate Install on (192.168.0.30) Server.NA Configuration With RAVIBhai And VaibhavBhai
and NEAT Plus Configuration And Installation With VibhavBhai and RaviBhai.

**Comment by Anil-Restalgo** [comment]
(NXBLOG(Delhi)) in this server SQL server installation Done And DataBase Import Successfully. And then All Exe and IIS Installation Pending.Hold By VaibhavBhai.

**Comment by Anil-Restalgo** [comment]
Now Start This task

**Comment by Anil-Restalgo** [comment]
(NXBLOG(Delhi)) in this server Install SQL Server DataBase Installation Done And DataBase SuccessFully Import in this Server In this Server IIS Installation Done IIS API Host Import Successfully.In This Server Admin Module EXE Done Client Trading System EXE Done Algo Spinner Exe Done FileDownload Exe Done NSEFO Delegate EXE Done RYDT Ops Engine EXE Done And BroadCast Also Done. In This Server All Installation Done. On Live Server and NSEFO Delegate Install on (NXBLOG(Delhi)) Server.

**Comment by Anil-Restalgo** [comment]
[Status of client Installation.xlsx](https://github.com/RestAlgo/TradingApplication/files/15403393/Status.of.client.Installation.xlsx)

**Comment by VIRAG-RestAlgo** [comment]
@Anil-Restalgo All Installation is done from our side and tested by me. that is Ok

But this is move to in process for today new deploy + trial order + admin module.

**Comment by VIRAG-RestAlgo** [comment]
Done by @Anil-Restalgo
