### ISSUE TITLE
Duplicate trade issue

### ISSUE THREAD

**Issue by VIRAG-RestAlgo** [RestAlgo/TradingApplication#99]

**Comment by VIRAG-RestAlgo** [comment]
when client re login at that time duplicate trade should not be add in tradebook and net position.

Please check as per discussed today.

**Comment by Kartik-RestAlgo** [comment]
Trade entry check and if no Trade found in tradeBookObjectInstance than add trade in tradeBookObjectInstance and publish while it

**Comment by Kartik-RestAlgo** [comment]
[Duplicate trade issue.pdf](https://github.com/RestAlgo/TradingApplication/files/15385330/Duplicate.trade.issue.pdf)

**Comment by VIRAG-RestAlgo** [comment]
Done. code merged.

**Comment by VIRAG-RestAlgo** [comment]
Check by Trade No. and update in live exe.
